///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomationSQLdm.TC_164838
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TC164838Repo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("110458ab-ec0b-4b90-88a4-0b1bfb85de4a")]
    public partial class TC164838Repo : RepoGenBaseFolder
    {
        static TC164838Repo instance = new TC164838Repo();
        TC164838RepoFolders.IderaSQLdmRepoAppFolder _iderasqldmrepo;
        TC164838RepoFolders.MonitoredSqlServerPropertiesAppFolder _monitoredsqlserverproperties;
        TC164838RepoFolders.AdvancedQueryMonitorConfigurationAppFolder _advancedquerymonitorconfiguration;

        /// <summary>
        /// Gets the singleton class instance representing the TC164838Repo element repository.
        /// </summary>
        [RepositoryFolder("110458ab-ec0b-4b90-88a4-0b1bfb85de4a")]
        public static TC164838Repo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TC164838Repo() 
            : base("TC164838Repo", "/", null, 0, false, "110458ab-ec0b-4b90-88a4-0b1bfb85de4a", ".\\RepositoryImages\\TC164838Repo110458ab.rximgres")
        {
            _iderasqldmrepo = new TC164838RepoFolders.IderaSQLdmRepoAppFolder(this);
            _monitoredsqlserverproperties = new TC164838RepoFolders.MonitoredSqlServerPropertiesAppFolder(this);
            _advancedquerymonitorconfiguration = new TC164838RepoFolders.AdvancedQueryMonitorConfigurationAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("110458ab-ec0b-4b90-88a4-0b1bfb85de4a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The IderaSQLdmRepo folder.
        /// </summary>
        [RepositoryFolder("f6be877a-cd91-42f4-91c9-ee24352d2989")]
        public virtual TC164838RepoFolders.IderaSQLdmRepoAppFolder IderaSQLdmRepo
        {
            get { return _iderasqldmrepo; }
        }

        /// <summary>
        /// The MonitoredSqlServerProperties folder.
        /// </summary>
        [RepositoryFolder("efd5a2a4-f54c-4152-b8f8-4b3386d87f07")]
        public virtual TC164838RepoFolders.MonitoredSqlServerPropertiesAppFolder MonitoredSqlServerProperties
        {
            get { return _monitoredsqlserverproperties; }
        }

        /// <summary>
        /// The AdvancedQueryMonitorConfiguration folder.
        /// </summary>
        [RepositoryFolder("a0b4afec-a397-4363-999f-31830eca88fd")]
        public virtual TC164838RepoFolders.AdvancedQueryMonitorConfigurationAppFolder AdvancedQueryMonitorConfiguration
        {
            get { return _advancedquerymonitorconfiguration; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class TC164838RepoFolders
    {
        /// <summary>
        /// The IderaSQLdmRepoAppFolder folder.
        /// </summary>
        [RepositoryFolder("f6be877a-cd91-42f4-91c9-ee24352d2989")]
        public partial class IderaSQLdmRepoAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnqueriesInfo;
            RepoItemInfo _btnconfigquerymonitorInfo;

            /// <summary>
            /// Creates a new IderaSQLdmRepo  folder.
            /// </summary>
            public IderaSQLdmRepoAppFolder(RepoGenBaseFolder parentFolder) :
                    base("IderaSQLdmRepo", "/form[@title~'^Idera\\ SQL\\ diagnostic\\ mana']", parentFolder, 30000, null, true, "f6be877a-cd91-42f4-91c9-ee24352d2989", "")
            {
                _btnqueriesInfo = new RepoItemInfo(this, "btnQueries", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Queries']/?/?/text[@caption='Queries']", 30000, null, "743421d4-ac79-416f-b0b3-5342aaeec405");
                _btnconfigquerymonitorInfo = new RepoItemInfo(this, "btnConfigQueryMonitor", ".//tabpage[@automationid='Queries']/toolbar[@automationid='queriesTabPropertiesGroup']/button", 30000, null, "a323cb77-c6e5-43eb-affe-4a9a83e8d58a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f6be877a-cd91-42f4-91c9-ee24352d2989")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f6be877a-cd91-42f4-91c9-ee24352d2989")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnQueries item.
            /// </summary>
            [RepositoryItem("743421d4-ac79-416f-b0b3-5342aaeec405")]
            public virtual Ranorex.Text btnQueries
            {
                get
                {
                    return _btnqueriesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The btnQueries item info.
            /// </summary>
            [RepositoryItemInfo("743421d4-ac79-416f-b0b3-5342aaeec405")]
            public virtual RepoItemInfo btnQueriesInfo
            {
                get
                {
                    return _btnqueriesInfo;
                }
            }

            /// <summary>
            /// The btnConfigQueryMonitor item.
            /// </summary>
            [RepositoryItem("a323cb77-c6e5-43eb-affe-4a9a83e8d58a")]
            public virtual Ranorex.Button btnConfigQueryMonitor
            {
                get
                {
                    return _btnconfigquerymonitorInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnConfigQueryMonitor item info.
            /// </summary>
            [RepositoryItemInfo("a323cb77-c6e5-43eb-affe-4a9a83e8d58a")]
            public virtual RepoItemInfo btnConfigQueryMonitorInfo
            {
                get
                {
                    return _btnconfigquerymonitorInfo;
                }
            }
        }

        /// <summary>
        /// The MonitoredSqlServerPropertiesAppFolder folder.
        /// </summary>
        [RepositoryFolder("efd5a2a4-f54c-4152-b8f8-4b3386d87f07")]
        public partial class MonitoredSqlServerPropertiesAppFolder : RepoGenBaseFolder
        {
            TC164838RepoFolders.QueryMonitorPropertyPageFolder _querymonitorpropertypage;
            TC164838RepoFolders.FmePoorlyPerformingThresholdsFolder _fmepoorlyperformingthresholds;
            RepoItemInfo _btnmsspokInfo;
            RepoItemInfo _btnmsspcancelInfo;

            /// <summary>
            /// Creates a new MonitoredSqlServerProperties  folder.
            /// </summary>
            public MonitoredSqlServerPropertiesAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MonitoredSqlServerProperties", "/form[@controlname='MonitoredSqlServerInstancePropertiesDialog']", parentFolder, 30000, null, true, "efd5a2a4-f54c-4152-b8f8-4b3386d87f07", "")
            {
                _querymonitorpropertypage = new TC164838RepoFolders.QueryMonitorPropertyPageFolder(this);
                _fmepoorlyperformingthresholds = new TC164838RepoFolders.FmePoorlyPerformingThresholdsFolder(this);
                _btnmsspokInfo = new RepoItemInfo(this, "btnMSSPOk", "button[@controlname='okButton']", 30000, null, "182666f0-a5ca-42ad-bfca-3dda36e10f25");
                _btnmsspcancelInfo = new RepoItemInfo(this, "btnMSSPCancel", "button[@controlname='cancelButton']", 30000, null, "f8a686c1-79f5-4882-9d97-ddc314cd396d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("efd5a2a4-f54c-4152-b8f8-4b3386d87f07")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("efd5a2a4-f54c-4152-b8f8-4b3386d87f07")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnMSSPOk item.
            /// </summary>
            [RepositoryItem("182666f0-a5ca-42ad-bfca-3dda36e10f25")]
            public virtual Ranorex.Button btnMSSPOk
            {
                get
                {
                    return _btnmsspokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnMSSPOk item info.
            /// </summary>
            [RepositoryItemInfo("182666f0-a5ca-42ad-bfca-3dda36e10f25")]
            public virtual RepoItemInfo btnMSSPOkInfo
            {
                get
                {
                    return _btnmsspokInfo;
                }
            }

            /// <summary>
            /// The btnMSSPCancel item.
            /// </summary>
            [RepositoryItem("f8a686c1-79f5-4882-9d97-ddc314cd396d")]
            public virtual Ranorex.Button btnMSSPCancel
            {
                get
                {
                    return _btnmsspcancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnMSSPCancel item info.
            /// </summary>
            [RepositoryItemInfo("f8a686c1-79f5-4882-9d97-ddc314cd396d")]
            public virtual RepoItemInfo btnMSSPCancelInfo
            {
                get
                {
                    return _btnmsspcancelInfo;
                }
            }

            /// <summary>
            /// The QueryMonitorPropertyPage folder.
            /// </summary>
            [RepositoryFolder("7fcd6a8e-838b-45f6-9e79-4f93066778ee")]
            public virtual TC164838RepoFolders.QueryMonitorPropertyPageFolder QueryMonitorPropertyPage
            {
                get { return _querymonitorpropertypage; }
            }

            /// <summary>
            /// The FmePoorlyPerformingThresholds folder.
            /// </summary>
            [RepositoryFolder("dee449ae-e1fe-46ce-bebf-fe260753ff90")]
            public virtual TC164838RepoFolders.FmePoorlyPerformingThresholdsFolder FmePoorlyPerformingThresholds
            {
                get { return _fmepoorlyperformingthresholds; }
            }
        }

        /// <summary>
        /// The QueryMonitorPropertyPageFolder folder.
        /// </summary>
        [RepositoryFolder("7fcd6a8e-838b-45f6-9e79-4f93066778ee")]
        public partial class QueryMonitorPropertyPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cbenablequerymonitorInfo;
            RepoItemInfo _rbcqdusingextendedeventsInfo;
            RepoItemInfo _rbcqdusingquerystoreInfo;
            RepoItemInfo _cbcollectqueryplansInfo;
            RepoItemInfo _cbcollectestimatedqueryplansInfo;
            RepoItemInfo _rbcqdusingsqltraceInfo;
            RepoItemInfo _btnqmadvancedoptionsInfo;

            /// <summary>
            /// Creates a new QueryMonitorPropertyPage  folder.
            /// </summary>
            public QueryMonitorPropertyPageFolder(RepoGenBaseFolder parentFolder) :
                    base("QueryMonitorPropertyPage", "container[@controlname='propertiesControl']//container[@controlname='queryMonitorPropertyPage']", parentFolder, 30000, null, false, "7fcd6a8e-838b-45f6-9e79-4f93066778ee", "")
            {
                _cbenablequerymonitorInfo = new RepoItemInfo(this, "cbEnableQueryMonitor", "?/?/container[@controlname='tableLayoutPanel17']/checkbox[@controlname='enableQueryMonitorTraceCheckBox']", 30000, null, "1b56ff22-52a4-4410-b1fe-8fb19a6eb5e8");
                _rbcqdusingextendedeventsInfo = new RepoItemInfo(this, "rbCQDUsingExtendedEvents", "?/?/container[@controlname='tableLayoutPanel19']/radiobutton[@controlname='rButtonUseExtendedEvents']", 30000, null, "1dc76323-e62a-4b5f-ad5f-1cd31332f55a");
                _rbcqdusingquerystoreInfo = new RepoItemInfo(this, "rbCQDUsingQueryStore", "?/?/container[@controlname='tableLayoutPanel19']/radiobutton[@controlname='rButtonUseQueryStore']", 30000, null, "9c96f059-8dba-41ca-aad4-0c00256a51f9");
                _cbcollectqueryplansInfo = new RepoItemInfo(this, "cbCollectQueryPlans", "?/?/container[@controlname='tableLayoutPanel19']/checkbox[@controlname='chkCollectQueryPlans']", 30000, null, "e9b86a84-1966-485f-8913-9ba3a20230bf");
                _cbcollectestimatedqueryplansInfo = new RepoItemInfo(this, "cbCollectEstimatedQueryPlans", "?/?/container[@controlname='tableLayoutPanel19']/checkbox[@controlname='chkCollectEstimatedQueryPlans']", 30000, null, "f20d6f1f-f903-49be-9bc5-2336fd323c0e");
                _rbcqdusingsqltraceInfo = new RepoItemInfo(this, "rbCQDUsingSQLTrace", "?/?/container[@controlname='tableLayoutPanel19']/radiobutton[@controlname='rButtonUseTrace']", 30000, null, "b6e5afe2-d63d-466b-9f6f-f2464ae93ab1");
                _btnqmadvancedoptionsInfo = new RepoItemInfo(this, "btnQMAdvancedOptions", "?/?/button[@controlname='queryMonitorAdvancedOptionsButton']", 30000, null, "2ce899ed-18f7-47db-b299-19c9db7f242c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7fcd6a8e-838b-45f6-9e79-4f93066778ee")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7fcd6a8e-838b-45f6-9e79-4f93066778ee")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The cbEnableQueryMonitor item.
            /// </summary>
            [RepositoryItem("1b56ff22-52a4-4410-b1fe-8fb19a6eb5e8")]
            public virtual Ranorex.CheckBox cbEnableQueryMonitor
            {
                get
                {
                    return _cbenablequerymonitorInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The cbEnableQueryMonitor item info.
            /// </summary>
            [RepositoryItemInfo("1b56ff22-52a4-4410-b1fe-8fb19a6eb5e8")]
            public virtual RepoItemInfo cbEnableQueryMonitorInfo
            {
                get
                {
                    return _cbenablequerymonitorInfo;
                }
            }

            /// <summary>
            /// The rbCQDUsingExtendedEvents item.
            /// </summary>
            [RepositoryItem("1dc76323-e62a-4b5f-ad5f-1cd31332f55a")]
            public virtual Ranorex.RadioButton rbCQDUsingExtendedEvents
            {
                get
                {
                    return _rbcqdusingextendedeventsInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rbCQDUsingExtendedEvents item info.
            /// </summary>
            [RepositoryItemInfo("1dc76323-e62a-4b5f-ad5f-1cd31332f55a")]
            public virtual RepoItemInfo rbCQDUsingExtendedEventsInfo
            {
                get
                {
                    return _rbcqdusingextendedeventsInfo;
                }
            }

            /// <summary>
            /// The rbCQDUsingQueryStore item.
            /// </summary>
            [RepositoryItem("9c96f059-8dba-41ca-aad4-0c00256a51f9")]
            public virtual Ranorex.RadioButton rbCQDUsingQueryStore
            {
                get
                {
                    return _rbcqdusingquerystoreInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rbCQDUsingQueryStore item info.
            /// </summary>
            [RepositoryItemInfo("9c96f059-8dba-41ca-aad4-0c00256a51f9")]
            public virtual RepoItemInfo rbCQDUsingQueryStoreInfo
            {
                get
                {
                    return _rbcqdusingquerystoreInfo;
                }
            }

            /// <summary>
            /// The cbCollectQueryPlans item.
            /// </summary>
            [RepositoryItem("e9b86a84-1966-485f-8913-9ba3a20230bf")]
            public virtual Ranorex.CheckBox cbCollectQueryPlans
            {
                get
                {
                    return _cbcollectqueryplansInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The cbCollectQueryPlans item info.
            /// </summary>
            [RepositoryItemInfo("e9b86a84-1966-485f-8913-9ba3a20230bf")]
            public virtual RepoItemInfo cbCollectQueryPlansInfo
            {
                get
                {
                    return _cbcollectqueryplansInfo;
                }
            }

            /// <summary>
            /// The cbCollectEstimatedQueryPlans item.
            /// </summary>
            [RepositoryItem("f20d6f1f-f903-49be-9bc5-2336fd323c0e")]
            public virtual Ranorex.CheckBox cbCollectEstimatedQueryPlans
            {
                get
                {
                    return _cbcollectestimatedqueryplansInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The cbCollectEstimatedQueryPlans item info.
            /// </summary>
            [RepositoryItemInfo("f20d6f1f-f903-49be-9bc5-2336fd323c0e")]
            public virtual RepoItemInfo cbCollectEstimatedQueryPlansInfo
            {
                get
                {
                    return _cbcollectestimatedqueryplansInfo;
                }
            }

            /// <summary>
            /// The rbCQDUsingSQLTrace item.
            /// </summary>
            [RepositoryItem("b6e5afe2-d63d-466b-9f6f-f2464ae93ab1")]
            public virtual Ranorex.RadioButton rbCQDUsingSQLTrace
            {
                get
                {
                    return _rbcqdusingsqltraceInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rbCQDUsingSQLTrace item info.
            /// </summary>
            [RepositoryItemInfo("b6e5afe2-d63d-466b-9f6f-f2464ae93ab1")]
            public virtual RepoItemInfo rbCQDUsingSQLTraceInfo
            {
                get
                {
                    return _rbcqdusingsqltraceInfo;
                }
            }

            /// <summary>
            /// The btnQMAdvancedOptions item.
            /// </summary>
            [RepositoryItem("2ce899ed-18f7-47db-b299-19c9db7f242c")]
            public virtual Ranorex.Button btnQMAdvancedOptions
            {
                get
                {
                    return _btnqmadvancedoptionsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnQMAdvancedOptions item info.
            /// </summary>
            [RepositoryItemInfo("2ce899ed-18f7-47db-b299-19c9db7f242c")]
            public virtual RepoItemInfo btnQMAdvancedOptionsInfo
            {
                get
                {
                    return _btnqmadvancedoptionsInfo;
                }
            }
        }

        /// <summary>
        /// The FmePoorlyPerformingThresholdsFolder folder.
        /// </summary>
        [RepositoryFolder("dee449ae-e1fe-46ce-bebf-fe260753ff90")]
        public partial class FmePoorlyPerformingThresholdsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtthdurationmsInfo;
            RepoItemInfo _txtthlogicaldiskreadsInfo;
            RepoItemInfo _txtthselecttopInfo;
            RepoItemInfo _txtthcpuusagemsInfo;
            RepoItemInfo _txtthphysicaldiskwritesInfo;
            RepoItemInfo _cbplansbyInfo;

            /// <summary>
            /// Creates a new FmePoorlyPerformingThresholds  folder.
            /// </summary>
            public FmePoorlyPerformingThresholdsFolder(RepoGenBaseFolder parentFolder) :
                    base("FmePoorlyPerformingThresholds", "container[@controlname='propertiesControl']//container[@controlname='tableLayoutPanel16']/container[@controlname='fmePoorlyPerformingThresholds']", parentFolder, 30000, null, false, "dee449ae-e1fe-46ce-bebf-fe260753ff90", "")
            {
                _txtthdurationmsInfo = new RepoItemInfo(this, "txtTHDurationMS", "?/?/container[@controlname='durationThresholdSpinner']/text[@controlname='upDownEdit']", 30000, null, "ede4b653-5deb-47dc-a384-b7067946181a");
                _txtthlogicaldiskreadsInfo = new RepoItemInfo(this, "txtTHLogicalDiskReads", "?/?/container[@controlname='logicalReadsThresholdSpinner']/text[@controlname='upDownEdit']", 30000, null, "626f391d-23f3-451b-aa69-598b4dc39ca4");
                _txtthselecttopInfo = new RepoItemInfo(this, "txtTHSelectTop", "?/?/container[@controlname='topPlanTableLayoutPanel']/container[@controlname='topPlanSpinner']/text[@controlname='upDownEdit']", 30000, null, "34b90c1c-8674-43d0-9842-b288db46f0c7");
                _txtthcpuusagemsInfo = new RepoItemInfo(this, "txtTHCPUUsageMS", "?/?/container[@controlname='cpuThresholdSpinner']/text[@controlname='upDownEdit']", 30000, null, "6e7e9166-6eff-4028-a920-0737dc38c183");
                _txtthphysicaldiskwritesInfo = new RepoItemInfo(this, "txtTHPhysicalDiskWrites", "?/?/container[@controlname='physicalWritesThresholdSpinner']/text[@controlname='upDownEdit']", 30000, null, "33350f3e-7fac-4053-9d73-f026cdd0eb96");
                _cbplansbyInfo = new RepoItemInfo(this, "CBPlansBy", "?/?/element[@controlname='topPlanComboBox']/combobox[@accessiblename='Plans by ']/combobox[@accessiblerole='ComboBox']", 30000, null, "68859223-941f-42ef-aaaa-d3b18d8ff4e5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dee449ae-e1fe-46ce-bebf-fe260753ff90")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dee449ae-e1fe-46ce-bebf-fe260753ff90")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txtTHDurationMS item.
            /// </summary>
            [RepositoryItem("ede4b653-5deb-47dc-a384-b7067946181a")]
            public virtual Ranorex.Text txtTHDurationMS
            {
                get
                {
                    return _txtthdurationmsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtTHDurationMS item info.
            /// </summary>
            [RepositoryItemInfo("ede4b653-5deb-47dc-a384-b7067946181a")]
            public virtual RepoItemInfo txtTHDurationMSInfo
            {
                get
                {
                    return _txtthdurationmsInfo;
                }
            }

            /// <summary>
            /// The txtTHLogicalDiskReads item.
            /// </summary>
            [RepositoryItem("626f391d-23f3-451b-aa69-598b4dc39ca4")]
            public virtual Ranorex.Text txtTHLogicalDiskReads
            {
                get
                {
                    return _txtthlogicaldiskreadsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtTHLogicalDiskReads item info.
            /// </summary>
            [RepositoryItemInfo("626f391d-23f3-451b-aa69-598b4dc39ca4")]
            public virtual RepoItemInfo txtTHLogicalDiskReadsInfo
            {
                get
                {
                    return _txtthlogicaldiskreadsInfo;
                }
            }

            /// <summary>
            /// The txtTHSelectTop item.
            /// </summary>
            [RepositoryItem("34b90c1c-8674-43d0-9842-b288db46f0c7")]
            public virtual Ranorex.Text txtTHSelectTop
            {
                get
                {
                    return _txtthselecttopInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtTHSelectTop item info.
            /// </summary>
            [RepositoryItemInfo("34b90c1c-8674-43d0-9842-b288db46f0c7")]
            public virtual RepoItemInfo txtTHSelectTopInfo
            {
                get
                {
                    return _txtthselecttopInfo;
                }
            }

            /// <summary>
            /// The txtTHCPUUsageMS item.
            /// </summary>
            [RepositoryItem("6e7e9166-6eff-4028-a920-0737dc38c183")]
            public virtual Ranorex.Text txtTHCPUUsageMS
            {
                get
                {
                    return _txtthcpuusagemsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtTHCPUUsageMS item info.
            /// </summary>
            [RepositoryItemInfo("6e7e9166-6eff-4028-a920-0737dc38c183")]
            public virtual RepoItemInfo txtTHCPUUsageMSInfo
            {
                get
                {
                    return _txtthcpuusagemsInfo;
                }
            }

            /// <summary>
            /// The txtTHPhysicalDiskWrites item.
            /// </summary>
            [RepositoryItem("33350f3e-7fac-4053-9d73-f026cdd0eb96")]
            public virtual Ranorex.Text txtTHPhysicalDiskWrites
            {
                get
                {
                    return _txtthphysicaldiskwritesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtTHPhysicalDiskWrites item info.
            /// </summary>
            [RepositoryItemInfo("33350f3e-7fac-4053-9d73-f026cdd0eb96")]
            public virtual RepoItemInfo txtTHPhysicalDiskWritesInfo
            {
                get
                {
                    return _txtthphysicaldiskwritesInfo;
                }
            }

            /// <summary>
            /// The CBPlansBy item.
            /// </summary>
            [RepositoryItem("68859223-941f-42ef-aaaa-d3b18d8ff4e5")]
            public virtual Ranorex.ComboBox CBPlansBy
            {
                get
                {
                    return _cbplansbyInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The CBPlansBy item info.
            /// </summary>
            [RepositoryItemInfo("68859223-941f-42ef-aaaa-d3b18d8ff4e5")]
            public virtual RepoItemInfo CBPlansByInfo
            {
                get
                {
                    return _cbplansbyInfo;
                }
            }
        }

        /// <summary>
        /// The AdvancedQueryMonitorConfigurationAppFolder folder.
        /// </summary>
        [RepositoryFolder("a0b4afec-a397-4363-999f-31830eca88fd")]
        public partial class AdvancedQueryMonitorConfigurationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cbexcludesqldmqueriesInfo;
            RepoItemInfo _btnaqmcokInfo;

            /// <summary>
            /// Creates a new AdvancedQueryMonitorConfiguration  folder.
            /// </summary>
            public AdvancedQueryMonitorConfigurationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AdvancedQueryMonitorConfiguration", "/form[@controlname='AdvancedQueryFilterConfigurationDialog']", parentFolder, 30000, null, true, "a0b4afec-a397-4363-999f-31830eca88fd", "")
            {
                _cbexcludesqldmqueriesInfo = new RepoItemInfo(this, "cbExcludeSQLDMQueries", "container[@controlname='propertiesControl1']//container[@controlname='propertyPage1']/container[@controlname='office2007PropertyPage1']//container[@controlname='panel1']/checkbox[@controlname='chkExcludeDM']", 30000, null, "51de21db-6a6a-4e49-ba63-af03f3a9a26d");
                _btnaqmcokInfo = new RepoItemInfo(this, "btnAQMCOk", "button[@controlname='okButton']", 30000, null, "71dda61a-4d0b-4d0d-b6ef-1755052fd817");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a0b4afec-a397-4363-999f-31830eca88fd")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a0b4afec-a397-4363-999f-31830eca88fd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The cbExcludeSQLDMQueries item.
            /// </summary>
            [RepositoryItem("51de21db-6a6a-4e49-ba63-af03f3a9a26d")]
            public virtual Ranorex.CheckBox cbExcludeSQLDMQueries
            {
                get
                {
                    return _cbexcludesqldmqueriesInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The cbExcludeSQLDMQueries item info.
            /// </summary>
            [RepositoryItemInfo("51de21db-6a6a-4e49-ba63-af03f3a9a26d")]
            public virtual RepoItemInfo cbExcludeSQLDMQueriesInfo
            {
                get
                {
                    return _cbexcludesqldmqueriesInfo;
                }
            }

            /// <summary>
            /// The btnAQMCOk item.
            /// </summary>
            [RepositoryItem("71dda61a-4d0b-4d0d-b6ef-1755052fd817")]
            public virtual Ranorex.Button btnAQMCOk
            {
                get
                {
                    return _btnaqmcokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnAQMCOk item info.
            /// </summary>
            [RepositoryItemInfo("71dda61a-4d0b-4d0d-b6ef-1755052fd817")]
            public virtual RepoItemInfo btnAQMCOkInfo
            {
                get
                {
                    return _btnaqmcokInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}