///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AutomationSQLdm.OperatorSecurityRole.TC_T721974
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("e461a081-13dd-49a1-be04-7dd1624076d3", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AutomationSQLdm.AutomationSQLdmRepository repository.
        /// </summary>
        public static AutomationSQLdm.AutomationSQLdmRepository repo = AutomationSQLdm.AutomationSQLdmRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddPermissionWizard.ContainerWizard1.AUTHOOVERSQL2012' at 113;6.", repo.AddPermissionWizard.ContainerWizard1.AUTHOOVERSQL2012Info, new RecordItemIndex(0));
            repo.AddPermissionWizard.ContainerWizard1.AUTHOOVERSQL2012.Click("113;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{LShiftKey down}' with focus on 'AddPermissionWizard.ContainerWizard1.AUTHOOVERSQL2012'.", repo.AddPermissionWizard.ContainerWizard1.AUTHOOVERSQL2012Info, new RecordItemIndex(1));
            repo.AddPermissionWizard.ContainerWizard1.AUTHOOVERSQL2012.PressKeys("{LControlKey down}{LShiftKey down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddPermissionWizard.ContainerWizard1.WIN10X6401' at 60;10.", repo.AddPermissionWizard.ContainerWizard1.WIN10X6401Info, new RecordItemIndex(2));
            repo.AddPermissionWizard.ContainerWizard1.WIN10X6401.Click("60;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey up}{LShiftKey up}' with focus on 'AddPermissionWizard.ContainerWizard1.WIN10X6401'.", repo.AddPermissionWizard.ContainerWizard1.WIN10X6401Info, new RecordItemIndex(3));
            repo.AddPermissionWizard.ContainerWizard1.WIN10X6401.PressKeys("{LControlKey up}{LShiftKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddPermissionWizard.ContainerWizard1.ButtonAdd' at 42;12.", repo.AddPermissionWizard.ContainerWizard1.ButtonAddInfo, new RecordItemIndex(4));
            repo.AddPermissionWizard.ContainerWizard1.ButtonAdd.Click("42;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(5));
            Delay.Duration(500, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
