///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomationSQLdm.Commons
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the CommonRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("9d2c49e9-5e4f-42bf-a8cf-910a588e3639")]
    public partial class CommonRepo : RepoGenBaseFolder
    {
        static CommonRepo instance = new CommonRepo();
        CommonRepoFolders.ApplicationAppFolder _application;

        /// <summary>
        /// Gets the singleton class instance representing the CommonRepo element repository.
        /// </summary>
        [RepositoryFolder("9d2c49e9-5e4f-42bf-a8cf-910a588e3639")]
        public static CommonRepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public CommonRepo() 
            : base("CommonRepo", "/", null, 0, false, "9d2c49e9-5e4f-42bf-a8cf-910a588e3639", ".\\RepositoryImages\\CommonRepo9d2c49e9.rximgres")
        {
            _application = new CommonRepoFolders.ApplicationAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("9d2c49e9-5e4f-42bf-a8cf-910a588e3639")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Application folder.
        /// </summary>
        [RepositoryFolder("1a73f651-c755-42fc-8b6e-622d9bbcf5f6")]
        public virtual CommonRepoFolders.ApplicationAppFolder Application
        {
            get { return _application; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class CommonRepoFolders
    {
        /// <summary>
        /// The ApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("1a73f651-c755-42fc-8b6e-622d9bbcf5f6")]
        public partial class ApplicationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _allserversInfo;

            /// <summary>
            /// Creates a new Application  folder.
            /// </summary>
            public ApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Application", "/form[@title~'^Idera\\ SQL\\ diagnostic\\ mana']", parentFolder, 30000, null, true, "1a73f651-c755-42fc-8b6e-622d9bbcf5f6", "")
            {
                _allserversInfo = new RepoItemInfo(this, "AllServers", ".//tree[@controlname='userViewTreeView']//treeitem[@accessiblename='All Servers']", 30000, null, "6945e911-73e0-44d3-b52f-f257cd63dbd9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1a73f651-c755-42fc-8b6e-622d9bbcf5f6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1a73f651-c755-42fc-8b6e-622d9bbcf5f6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AllServers item.
            /// </summary>
            [RepositoryItem("6945e911-73e0-44d3-b52f-f257cd63dbd9")]
            public virtual Ranorex.TreeItem AllServers
            {
                get
                {
                    return _allserversInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The AllServers item info.
            /// </summary>
            [RepositoryItemInfo("6945e911-73e0-44d3-b52f-f257cd63dbd9")]
            public virtual RepoItemInfo AllServersInfo
            {
                get
                {
                    return _allserversInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}