///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomationSQLdm
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AutomationSQLdmRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("7bd21acd-09e4-4c42-81c5-68b39ccd889b")]
    public partial class AutomationSQLdmRepository : RepoGenBaseFolder
    {
        static AutomationSQLdmRepository instance = new AutomationSQLdmRepository();
        AutomationSQLdmRepositoryFolders.AddPermissionWizardAppFolder _addpermissionwizard;

        /// <summary>
        /// Gets the singleton class instance representing the AutomationSQLdmRepository element repository.
        /// </summary>
        [RepositoryFolder("7bd21acd-09e4-4c42-81c5-68b39ccd889b")]
        public static AutomationSQLdmRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AutomationSQLdmRepository() 
            : base("AutomationSQLdmRepository", "/", null, 0, false, "7bd21acd-09e4-4c42-81c5-68b39ccd889b", ".\\RepositoryImages\\AutomationSQLdmRepository7bd21acd.rximgres")
        {
            _addpermissionwizard = new AutomationSQLdmRepositoryFolders.AddPermissionWizardAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("7bd21acd-09e4-4c42-81c5-68b39ccd889b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The AddPermissionWizard folder.
        /// </summary>
        [RepositoryFolder("9e58868c-5494-43f0-bef4-1afb3d150112")]
        public virtual AutomationSQLdmRepositoryFolders.AddPermissionWizardAppFolder AddPermissionWizard
        {
            get { return _addpermissionwizard; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class AutomationSQLdmRepositoryFolders
    {
        /// <summary>
        /// The AddPermissionWizardAppFolder folder.
        /// </summary>
        [RepositoryFolder("9e58868c-5494-43f0-bef4-1afb3d150112")]
        public partial class AddPermissionWizardAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _jsxw7s8sql2008Info;

            /// <summary>
            /// Creates a new AddPermissionWizard  folder.
            /// </summary>
            public AddPermissionWizardAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AddPermissionWizard", "/form[@controlname='AddPermissionWizard']", parentFolder, 30000, null, true, "9e58868c-5494-43f0-bef4-1afb3d150112", "")
            {
                _jsxw7s8sql2008Info = new RepoItemInfo(this, "JSXW7S8SQL2008", "container[@controlname='_wizard']//list[@controlname='listBoxAvailable']/list[@accessiblename='Selected Servers:']/listitem[@accessiblename='JS-XW7S8\\SQL2008']", 30000, null, "44e4224c-d691-4676-9767-ca1d9a6f2319");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9e58868c-5494-43f0-bef4-1afb3d150112")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9e58868c-5494-43f0-bef4-1afb3d150112")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The JSXW7S8SQL2008 item.
            /// </summary>
            [RepositoryItem("44e4224c-d691-4676-9767-ca1d9a6f2319")]
            public virtual Ranorex.ListItem JSXW7S8SQL2008
            {
                get
                {
                    return _jsxw7s8sql2008Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The JSXW7S8SQL2008 item info.
            /// </summary>
            [RepositoryItemInfo("44e4224c-d691-4676-9767-ca1d9a6f2319")]
            public virtual RepoItemInfo JSXW7S8SQL2008Info
            {
                get
                {
                    return _jsxw7s8sql2008Info;
                }
            }
        }

    }
#pragma warning restore 0436
}