///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomationSQLdm.OperatorSecurityRole
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the OperatorSecurityRoleRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("c0b1886f-194f-4804-ae68-99f28ac1402e")]
    public partial class OperatorSecurityRoleRepo : RepoGenBaseFolder
    {
        static OperatorSecurityRoleRepo instance = new OperatorSecurityRoleRepo();
        OperatorSecurityRoleRepoFolders.ApplicationAppFolder _application;
        OperatorSecurityRoleRepoFolders.ExceptionFormAppFolder _exceptionform;
        OperatorSecurityRoleRepoFolders.AddPermissionWizardAppFolder _addpermissionwizard;
        OperatorSecurityRoleRepoFolders.PermissionPropertyDialogAppFolder _permissionpropertydialog;
        OperatorSecurityRoleRepoFolders.SQLdmDesktopClientAppFolder _sqldmdesktopclient;
        OperatorSecurityRoleRepoFolders.SnoozeAlertsDialogAppFolder _snoozealertsdialog;
        OperatorSecurityRoleRepoFolders.RepositoryConnectionDialogAppFolder _repositoryconnectiondialog;
        OperatorSecurityRoleRepoFolders.List1000AppFolder _list1000;

        /// <summary>
        /// Gets the singleton class instance representing the OperatorSecurityRoleRepo element repository.
        /// </summary>
        [RepositoryFolder("c0b1886f-194f-4804-ae68-99f28ac1402e")]
        public static OperatorSecurityRoleRepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public OperatorSecurityRoleRepo() 
            : base("OperatorSecurityRoleRepo", "/", null, 0, false, "c0b1886f-194f-4804-ae68-99f28ac1402e", ".\\RepositoryImages\\OperatorSecurityRoleRepoc0b1886f.rximgres")
        {
            _application = new OperatorSecurityRoleRepoFolders.ApplicationAppFolder(this);
            _exceptionform = new OperatorSecurityRoleRepoFolders.ExceptionFormAppFolder(this);
            _addpermissionwizard = new OperatorSecurityRoleRepoFolders.AddPermissionWizardAppFolder(this);
            _permissionpropertydialog = new OperatorSecurityRoleRepoFolders.PermissionPropertyDialogAppFolder(this);
            _sqldmdesktopclient = new OperatorSecurityRoleRepoFolders.SQLdmDesktopClientAppFolder(this);
            _snoozealertsdialog = new OperatorSecurityRoleRepoFolders.SnoozeAlertsDialogAppFolder(this);
            _repositoryconnectiondialog = new OperatorSecurityRoleRepoFolders.RepositoryConnectionDialogAppFolder(this);
            _list1000 = new OperatorSecurityRoleRepoFolders.List1000AppFolder(this);
        }

#region Variables

        string _Constant_NewSqlUser = "";

        /// <summary>
        /// Gets or sets the value of variable Constant_NewSqlUser.
        /// </summary>
        [TestVariable("971340c3-a4a0-47b8-9d3b-fefd2c554fc1")]
        public string Constant_NewSqlUser
        {
            get { return _Constant_NewSqlUser; }
            set { _Constant_NewSqlUser = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c0b1886f-194f-4804-ae68-99f28ac1402e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Application folder.
        /// </summary>
        [RepositoryFolder("1a73f651-c755-42fc-8b6e-622d9bbcf5f6")]
        public virtual OperatorSecurityRoleRepoFolders.ApplicationAppFolder Application
        {
            get { return _application; }
        }

        /// <summary>
        /// The ExceptionForm folder.
        /// </summary>
        [RepositoryFolder("03260382-2f67-4d48-814d-38cb9e95e8d7")]
        public virtual OperatorSecurityRoleRepoFolders.ExceptionFormAppFolder ExceptionForm
        {
            get { return _exceptionform; }
        }

        /// <summary>
        /// The AddPermissionWizard folder.
        /// </summary>
        [RepositoryFolder("a22e5f92-0bb1-4450-adc1-c7b9588f7fac")]
        public virtual OperatorSecurityRoleRepoFolders.AddPermissionWizardAppFolder AddPermissionWizard
        {
            get { return _addpermissionwizard; }
        }

        /// <summary>
        /// The PermissionPropertyDialog folder.
        /// </summary>
        [RepositoryFolder("add75c9c-387f-4f83-b594-6e44d91f4f68")]
        public virtual OperatorSecurityRoleRepoFolders.PermissionPropertyDialogAppFolder PermissionPropertyDialog
        {
            get { return _permissionpropertydialog; }
        }

        /// <summary>
        /// The SQLdmDesktopClient folder.
        /// </summary>
        [RepositoryFolder("9545f389-3161-4094-a144-bf9e8a5703bd")]
        public virtual OperatorSecurityRoleRepoFolders.SQLdmDesktopClientAppFolder SQLdmDesktopClient
        {
            get { return _sqldmdesktopclient; }
        }

        /// <summary>
        /// The SnoozeAlertsDialog folder.
        /// </summary>
        [RepositoryFolder("279bc91f-42af-40fc-a5aa-4e25b06755dc")]
        public virtual OperatorSecurityRoleRepoFolders.SnoozeAlertsDialogAppFolder SnoozeAlertsDialog
        {
            get { return _snoozealertsdialog; }
        }

        /// <summary>
        /// The RepositoryConnectionDialog folder.
        /// </summary>
        [RepositoryFolder("045423ee-b2db-4e1b-9c8a-6f1ff05a9a01")]
        public virtual OperatorSecurityRoleRepoFolders.RepositoryConnectionDialogAppFolder RepositoryConnectionDialog
        {
            get { return _repositoryconnectiondialog; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("97290bd8-21d4-4e4f-88b1-a8cf119886e4")]
        public virtual OperatorSecurityRoleRepoFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class OperatorSecurityRoleRepoFolders
    {
        /// <summary>
        /// The ApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("1a73f651-c755-42fc-8b6e-622d9bbcf5f6")]
        public partial class ApplicationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnadministrationInfo;
            RepoItemInfo _enablesecurityInfo;
            RepoItemInfo _applicationsecurityInfo;
            RepoItemInfo _btnaddusersInfo;
            RepoItemInfo _newwindowsuseraddedInfo;
            RepoItemInfo _btndeleteInfo;
            RepoItemInfo _newsqluseraddedInfo;
            RepoItemInfo _allserversInfo;
            RepoItemInfo _serversInfo;
            RepoItemInfo _sqldmtodayInfo;
            RepoItemInfo _allserversareinmaintenancemodeInfo;
            RepoItemInfo _fileInfo;
            RepoItemInfo _captiontextInfo;

            /// <summary>
            /// Creates a new Application  folder.
            /// </summary>
            public ApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Application", "/form[@title~'^Idera\\ SQL\\ diagnostic\\ mana']", parentFolder, 30000, null, true, "1a73f651-c755-42fc-8b6e-622d9bbcf5f6", "")
            {
                _btnadministrationInfo = new RepoItemInfo(this, "btnAdministration", "statusbar[@automationid='statusBar']//container[@controlname='NavigationPaneControl']//button[@accessiblename='Administration']", 30000, null, "d5152b0d-4009-43f3-bc98-69da8be4ca7c");
                _enablesecurityInfo = new RepoItemInfo(this, "EnableSecurity", "statusbar[@automationid='statusBar']//container[@controlname='AdministrationView']//button[@accessiblename='Enable Security']", 30000, null, "f5eb38d9-4a59-4bf5-a1cc-3c7fe3ab33ab");
                _applicationsecurityInfo = new RepoItemInfo(this, "ApplicationSecurity", ".//container[@controlname='featureButtonAppSecurity']//text[@controlname='featureHeaderLabel']", 30000, null, "7beca8f1-156e-42cd-9e29-76177c54937a");
                _btnaddusersInfo = new RepoItemInfo(this, "btnAddUsers", ".//container[@controlname='contentPanel']//container[@accessiblename='Home']/toolbar[@accessiblename='Permissions']/button[@accessiblename='Add']", 30000, null, "d0736455-ddb6-4eea-aa8a-f74408840be1");
                _newwindowsuseraddedInfo = new RepoItemInfo(this, "NewWindowsUserAdded", "statusbar[@automationid='statusBar']//table[@accessiblename~'^\\ \\ \\ \\ \\ \\ \\ System\\ logins,\\ whi']//cell[@accessiblevalue='SIMPSONS\\administrator1']", 30000, null, "e83e5dc8-2e44-4b06-8733-50f149243c29");
                _btndeleteInfo = new RepoItemInfo(this, "btnDelete", "statusbar[@automationid='statusBar']//toolbar[@accessiblename='Permissions']/button[@accessiblename='Delete']", 30000, null, "f91739cf-b4a3-4344-a6d1-ce64cd55d567");
                _newsqluseraddedInfo = new RepoItemInfo(this, "NewSqlUserAdded", "statusbar[@automationid='statusBar']//table[@accessiblename~'^\\ \\ \\ \\ \\ \\ \\ System\\ logins,\\ whi']//cell[@accessiblevalue='sa1']", 30000, null, "172570af-8ff7-4fe3-85cb-8980091f5933");
                _allserversInfo = new RepoItemInfo(this, "AllServers", ".//tree[@controlname='userViewTreeView']//treeitem[@accessiblename='All Servers']", 30000, null, "5f08e6b7-a10a-4f65-9e1c-fe874145609f");
                _serversInfo = new RepoItemInfo(this, "Servers", "statusbar[@automationid='statusBar']//container[@automationid='navigationPaneHost']//container[@controlname='NavigationPaneControl']//button[@accessiblename='Servers']", 30000, null, "ff1ed87b-54ce-425a-bd29-0d68843551f3");
                _sqldmtodayInfo = new RepoItemInfo(this, "SQLDMToday", "statusbar[@automationid='statusBar']//button[@automationid='toolBarTodayButton']/text[@caption='SQLDM Today']", 30000, null, "5bf580d6-74dd-4c4e-8621-62765e9408f9");
                _allserversareinmaintenancemodeInfo = new RepoItemInfo(this, "AllServersAreInMaintenanceMode", ".//link[@controlname='statusSummaryDescriptionLabel']//link[@accessiblename~'^All\\ servers\\ are\\ in\\ mainte']", 30000, null, "0de91f77-1b72-475d-b7dc-323b95580868");
                _fileInfo = new RepoItemInfo(this, "File", ".//list[@automationid='fileMenu']/picture[@automationid='HeaderPresenter']/text[@caption='File']", 30000, null, "0f4ec73c-5da5-467a-a21b-741d46fe8523");
                _captiontextInfo = new RepoItemInfo(this, "CaptionText", "?/?/picture[@automationid='PART_WindowIcon']/text[@automationid='CaptionText']", 30000, null, "d79840b0-5e62-4ac0-a6b0-730140cf095e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1a73f651-c755-42fc-8b6e-622d9bbcf5f6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1a73f651-c755-42fc-8b6e-622d9bbcf5f6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnAdministration item.
            /// </summary>
            [RepositoryItem("d5152b0d-4009-43f3-bc98-69da8be4ca7c")]
            public virtual Ranorex.Button btnAdministration
            {
                get
                {
                    return _btnadministrationInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnAdministration item info.
            /// </summary>
            [RepositoryItemInfo("d5152b0d-4009-43f3-bc98-69da8be4ca7c")]
            public virtual RepoItemInfo btnAdministrationInfo
            {
                get
                {
                    return _btnadministrationInfo;
                }
            }

            /// <summary>
            /// The EnableSecurity item.
            /// </summary>
            [RepositoryItem("f5eb38d9-4a59-4bf5-a1cc-3c7fe3ab33ab")]
            public virtual Ranorex.Button EnableSecurity
            {
                get
                {
                    return _enablesecurityInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EnableSecurity item info.
            /// </summary>
            [RepositoryItemInfo("f5eb38d9-4a59-4bf5-a1cc-3c7fe3ab33ab")]
            public virtual RepoItemInfo EnableSecurityInfo
            {
                get
                {
                    return _enablesecurityInfo;
                }
            }

            /// <summary>
            /// The ApplicationSecurity item.
            /// </summary>
            [RepositoryItem("7beca8f1-156e-42cd-9e29-76177c54937a")]
            public virtual Ranorex.Text ApplicationSecurity
            {
                get
                {
                    return _applicationsecurityInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ApplicationSecurity item info.
            /// </summary>
            [RepositoryItemInfo("7beca8f1-156e-42cd-9e29-76177c54937a")]
            public virtual RepoItemInfo ApplicationSecurityInfo
            {
                get
                {
                    return _applicationsecurityInfo;
                }
            }

            /// <summary>
            /// The btnAddUsers item.
            /// </summary>
            [RepositoryItem("d0736455-ddb6-4eea-aa8a-f74408840be1")]
            public virtual Ranorex.Button btnAddUsers
            {
                get
                {
                    return _btnaddusersInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnAddUsers item info.
            /// </summary>
            [RepositoryItemInfo("d0736455-ddb6-4eea-aa8a-f74408840be1")]
            public virtual RepoItemInfo btnAddUsersInfo
            {
                get
                {
                    return _btnaddusersInfo;
                }
            }

            /// <summary>
            /// The NewWindowsUserAdded item.
            /// </summary>
            [RepositoryItem("e83e5dc8-2e44-4b06-8733-50f149243c29")]
            public virtual Ranorex.Cell NewWindowsUserAdded
            {
                get
                {
                    return _newwindowsuseraddedInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The NewWindowsUserAdded item info.
            /// </summary>
            [RepositoryItemInfo("e83e5dc8-2e44-4b06-8733-50f149243c29")]
            public virtual RepoItemInfo NewWindowsUserAddedInfo
            {
                get
                {
                    return _newwindowsuseraddedInfo;
                }
            }

            /// <summary>
            /// The btnDelete item.
            /// </summary>
            [RepositoryItem("f91739cf-b4a3-4344-a6d1-ce64cd55d567")]
            public virtual Ranorex.Button btnDelete
            {
                get
                {
                    return _btndeleteInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnDelete item info.
            /// </summary>
            [RepositoryItemInfo("f91739cf-b4a3-4344-a6d1-ce64cd55d567")]
            public virtual RepoItemInfo btnDeleteInfo
            {
                get
                {
                    return _btndeleteInfo;
                }
            }

            /// <summary>
            /// The NewSqlUserAdded item.
            /// </summary>
            [RepositoryItem("172570af-8ff7-4fe3-85cb-8980091f5933")]
            public virtual Ranorex.Cell NewSqlUserAdded
            {
                get
                {
                    return _newsqluseraddedInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The NewSqlUserAdded item info.
            /// </summary>
            [RepositoryItemInfo("172570af-8ff7-4fe3-85cb-8980091f5933")]
            public virtual RepoItemInfo NewSqlUserAddedInfo
            {
                get
                {
                    return _newsqluseraddedInfo;
                }
            }

            /// <summary>
            /// The AllServers item.
            /// </summary>
            [RepositoryItem("5f08e6b7-a10a-4f65-9e1c-fe874145609f")]
            public virtual Ranorex.TreeItem AllServers
            {
                get
                {
                    return _allserversInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The AllServers item info.
            /// </summary>
            [RepositoryItemInfo("5f08e6b7-a10a-4f65-9e1c-fe874145609f")]
            public virtual RepoItemInfo AllServersInfo
            {
                get
                {
                    return _allserversInfo;
                }
            }

            /// <summary>
            /// The Servers item.
            /// </summary>
            [RepositoryItem("ff1ed87b-54ce-425a-bd29-0d68843551f3")]
            public virtual Ranorex.Button Servers
            {
                get
                {
                    return _serversInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Servers item info.
            /// </summary>
            [RepositoryItemInfo("ff1ed87b-54ce-425a-bd29-0d68843551f3")]
            public virtual RepoItemInfo ServersInfo
            {
                get
                {
                    return _serversInfo;
                }
            }

            /// <summary>
            /// The SQLDMToday item.
            /// </summary>
            [RepositoryItem("5bf580d6-74dd-4c4e-8621-62765e9408f9")]
            public virtual Ranorex.Text SQLDMToday
            {
                get
                {
                    return _sqldmtodayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SQLDMToday item info.
            /// </summary>
            [RepositoryItemInfo("5bf580d6-74dd-4c4e-8621-62765e9408f9")]
            public virtual RepoItemInfo SQLDMTodayInfo
            {
                get
                {
                    return _sqldmtodayInfo;
                }
            }

            /// <summary>
            /// The AllServersAreInMaintenanceMode item.
            /// </summary>
            [RepositoryItem("0de91f77-1b72-475d-b7dc-323b95580868")]
            public virtual Ranorex.Link AllServersAreInMaintenanceMode
            {
                get
                {
                    return _allserversareinmaintenancemodeInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The AllServersAreInMaintenanceMode item info.
            /// </summary>
            [RepositoryItemInfo("0de91f77-1b72-475d-b7dc-323b95580868")]
            public virtual RepoItemInfo AllServersAreInMaintenanceModeInfo
            {
                get
                {
                    return _allserversareinmaintenancemodeInfo;
                }
            }

            /// <summary>
            /// The File item.
            /// </summary>
            [RepositoryItem("0f4ec73c-5da5-467a-a21b-741d46fe8523")]
            public virtual Ranorex.Text File
            {
                get
                {
                    return _fileInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The File item info.
            /// </summary>
            [RepositoryItemInfo("0f4ec73c-5da5-467a-a21b-741d46fe8523")]
            public virtual RepoItemInfo FileInfo
            {
                get
                {
                    return _fileInfo;
                }
            }

            /// <summary>
            /// The CaptionText item.
            /// </summary>
            [RepositoryItem("d79840b0-5e62-4ac0-a6b0-730140cf095e")]
            public virtual Ranorex.Text CaptionText
            {
                get
                {
                    return _captiontextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CaptionText item info.
            /// </summary>
            [RepositoryItemInfo("d79840b0-5e62-4ac0-a6b0-730140cf095e")]
            public virtual RepoItemInfo CaptionTextInfo
            {
                get
                {
                    return _captiontextInfo;
                }
            }
        }

        /// <summary>
        /// The ExceptionFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("03260382-2f67-4d48-814d-38cb9e95e8d7")]
        public partial class ExceptionFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnyesInfo;

            /// <summary>
            /// Creates a new ExceptionForm  folder.
            /// </summary>
            public ExceptionFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ExceptionForm", "/form[@controlname='ExceptionMessageBoxForm']", parentFolder, 30000, null, true, "03260382-2f67-4d48-814d-38cb9e95e8d7", "")
            {
                _btnyesInfo = new RepoItemInfo(this, "btnYes", ".//button[@windowtext='&Yes']", 30000, null, "c5426114-da69-4c53-97eb-481dfbebee4b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("03260382-2f67-4d48-814d-38cb9e95e8d7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("03260382-2f67-4d48-814d-38cb9e95e8d7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnYes item.
            /// </summary>
            [RepositoryItem("c5426114-da69-4c53-97eb-481dfbebee4b")]
            public virtual Ranorex.Button btnYes
            {
                get
                {
                    return _btnyesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnYes item info.
            /// </summary>
            [RepositoryItemInfo("c5426114-da69-4c53-97eb-481dfbebee4b")]
            public virtual RepoItemInfo btnYesInfo
            {
                get
                {
                    return _btnyesInfo;
                }
            }
        }

        /// <summary>
        /// The AddPermissionWizardAppFolder folder.
        /// </summary>
        [RepositoryFolder("a22e5f92-0bb1-4450-adc1-c7b9588f7fac")]
        public partial class AddPermissionWizardAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnnextInfo;
            RepoItemInfo _txtusernameInfo;
            RepoItemInfo _viewdataacknowledgwalarmInfo;
            RepoItemInfo _availableserversInfo;
            RepoItemInfo _buttonaddInfo;
            RepoItemInfo _buttonfinishInfo;
            RepoItemInfo _comboboxuserpagecmbbxauthenticationInfo;

            /// <summary>
            /// Creates a new AddPermissionWizard  folder.
            /// </summary>
            public AddPermissionWizardAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AddPermissionWizard", "/form[@controlname='AddPermissionWizard']", parentFolder, 30000, null, true, "a22e5f92-0bb1-4450-adc1-c7b9588f7fac", "")
            {
                _btnnextInfo = new RepoItemInfo(this, "btnNext", ".//button[@windowtext='&Next >']", 30000, null, "b6d30a78-1b49-4eb7-8236-6f4bebfac5cc");
                _txtusernameInfo = new RepoItemInfo(this, "txtUserName", "container[@controlname='_wizard']//text[@accessiblerole='Text']", 30000, null, "3f200e22-97eb-4912-98b9-b25b78ec61d7");
                _viewdataacknowledgwalarmInfo = new RepoItemInfo(this, "ViewDataAcknowledgwAlarm", "container[@controlname='_wizard']//radiobutton[@controlname='_permissionPageRdBtnReadOnlyPlus']", 30000, null, "fce969f7-f146-4767-ba28-711b708ee06a");
                _availableserversInfo = new RepoItemInfo(this, "AvailableServers", "container[@controlname='_wizard']//container[@controlname='_serversListSelectorControl']//list[@controlname='listBoxAvailable']", 30000, null, "7a396840-f02f-4960-aaab-3ff9800f57cb");
                _buttonaddInfo = new RepoItemInfo(this, "ButtonAdd", "container[@controlname='_wizard']//container[@controlname='tableLayoutPanel2']/button[@controlname='buttonAdd']", 30000, null, "62e75094-e409-4073-9734-0795032f3f0f");
                _buttonfinishInfo = new RepoItemInfo(this, "ButtonFinish", ".//button[@text='Finish']", 30000, null, "dff72719-a352-42e6-be7d-349d3ce825a7");
                _comboboxuserpagecmbbxauthenticationInfo = new RepoItemInfo(this, "ComboBoxUserPageCmbBxAuthentication", "container[@controlname='_wizard']//combobox[@controlname='_userPageCmbBxAuthentication']", 30000, null, "01141426-8c31-45b3-b8d8-e14b26cd328f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a22e5f92-0bb1-4450-adc1-c7b9588f7fac")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a22e5f92-0bb1-4450-adc1-c7b9588f7fac")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnNext item.
            /// </summary>
            [RepositoryItem("b6d30a78-1b49-4eb7-8236-6f4bebfac5cc")]
            public virtual Ranorex.Button btnNext
            {
                get
                {
                    return _btnnextInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnNext item info.
            /// </summary>
            [RepositoryItemInfo("b6d30a78-1b49-4eb7-8236-6f4bebfac5cc")]
            public virtual RepoItemInfo btnNextInfo
            {
                get
                {
                    return _btnnextInfo;
                }
            }

            /// <summary>
            /// The txtUserName item.
            /// </summary>
            [RepositoryItem("3f200e22-97eb-4912-98b9-b25b78ec61d7")]
            public virtual Ranorex.Text txtUserName
            {
                get
                {
                    return _txtusernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtUserName item info.
            /// </summary>
            [RepositoryItemInfo("3f200e22-97eb-4912-98b9-b25b78ec61d7")]
            public virtual RepoItemInfo txtUserNameInfo
            {
                get
                {
                    return _txtusernameInfo;
                }
            }

            /// <summary>
            /// The ViewDataAcknowledgwAlarm item.
            /// </summary>
            [RepositoryItem("fce969f7-f146-4767-ba28-711b708ee06a")]
            public virtual Ranorex.RadioButton ViewDataAcknowledgwAlarm
            {
                get
                {
                    return _viewdataacknowledgwalarmInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The ViewDataAcknowledgwAlarm item info.
            /// </summary>
            [RepositoryItemInfo("fce969f7-f146-4767-ba28-711b708ee06a")]
            public virtual RepoItemInfo ViewDataAcknowledgwAlarmInfo
            {
                get
                {
                    return _viewdataacknowledgwalarmInfo;
                }
            }

            /// <summary>
            /// The AvailableServers item.
            /// </summary>
            [RepositoryItem("7a396840-f02f-4960-aaab-3ff9800f57cb")]
            public virtual Ranorex.List AvailableServers
            {
                get
                {
                    return _availableserversInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The AvailableServers item info.
            /// </summary>
            [RepositoryItemInfo("7a396840-f02f-4960-aaab-3ff9800f57cb")]
            public virtual RepoItemInfo AvailableServersInfo
            {
                get
                {
                    return _availableserversInfo;
                }
            }

            /// <summary>
            /// The ButtonAdd item.
            /// </summary>
            [RepositoryItem("62e75094-e409-4073-9734-0795032f3f0f")]
            public virtual Ranorex.Button ButtonAdd
            {
                get
                {
                    return _buttonaddInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonAdd item info.
            /// </summary>
            [RepositoryItemInfo("62e75094-e409-4073-9734-0795032f3f0f")]
            public virtual RepoItemInfo ButtonAddInfo
            {
                get
                {
                    return _buttonaddInfo;
                }
            }

            /// <summary>
            /// The ButtonFinish item.
            /// </summary>
            [RepositoryItem("dff72719-a352-42e6-be7d-349d3ce825a7")]
            public virtual Ranorex.Button ButtonFinish
            {
                get
                {
                    return _buttonfinishInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonFinish item info.
            /// </summary>
            [RepositoryItemInfo("dff72719-a352-42e6-be7d-349d3ce825a7")]
            public virtual RepoItemInfo ButtonFinishInfo
            {
                get
                {
                    return _buttonfinishInfo;
                }
            }

            /// <summary>
            /// The ComboBoxUserPageCmbBxAuthentication item.
            /// </summary>
            [RepositoryItem("01141426-8c31-45b3-b8d8-e14b26cd328f")]
            public virtual Ranorex.ComboBox ComboBoxUserPageCmbBxAuthentication
            {
                get
                {
                    return _comboboxuserpagecmbbxauthenticationInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBoxUserPageCmbBxAuthentication item info.
            /// </summary>
            [RepositoryItemInfo("01141426-8c31-45b3-b8d8-e14b26cd328f")]
            public virtual RepoItemInfo ComboBoxUserPageCmbBxAuthenticationInfo
            {
                get
                {
                    return _comboboxuserpagecmbbxauthenticationInfo;
                }
            }
        }

        /// <summary>
        /// The PermissionPropertyDialogAppFolder folder.
        /// </summary>
        [RepositoryFolder("add75c9c-387f-4f83-b594-6e44d91f4f68")]
        public partial class PermissionPropertyDialogAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btncancelInfo;
            RepoItemInfo _viewdataacknowledgwalarmInfo;

            /// <summary>
            /// Creates a new PermissionPropertyDialog  folder.
            /// </summary>
            public PermissionPropertyDialogAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PermissionPropertyDialog", "/form[@controlname='PermissionPropertyDialog']", parentFolder, 30000, null, true, "add75c9c-387f-4f83-b594-6e44d91f4f68", "")
            {
                _btncancelInfo = new RepoItemInfo(this, "btnCancel", "button[@controlname='_btnCancel']", 30000, null, "dfc1df6d-ec71-475d-8512-a56ded9c334d");
                _viewdataacknowledgwalarmInfo = new RepoItemInfo(this, "ViewDataAcknowledgwAlarm", ".//container[@controlname='_generalPropertyPage']//radiobutton[@controlname='_generalRdBtnReadOnlyPlus']", 30000, null, "7be52f43-2cea-4c12-b472-9fa8a26afb76");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("add75c9c-387f-4f83-b594-6e44d91f4f68")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("add75c9c-387f-4f83-b594-6e44d91f4f68")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnCancel item.
            /// </summary>
            [RepositoryItem("dfc1df6d-ec71-475d-8512-a56ded9c334d")]
            public virtual Ranorex.Button btnCancel
            {
                get
                {
                    return _btncancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnCancel item info.
            /// </summary>
            [RepositoryItemInfo("dfc1df6d-ec71-475d-8512-a56ded9c334d")]
            public virtual RepoItemInfo btnCancelInfo
            {
                get
                {
                    return _btncancelInfo;
                }
            }

            /// <summary>
            /// The ViewDataAcknowledgwAlarm item.
            /// </summary>
            [RepositoryItem("7be52f43-2cea-4c12-b472-9fa8a26afb76")]
            public virtual Ranorex.RadioButton ViewDataAcknowledgwAlarm
            {
                get
                {
                    return _viewdataacknowledgwalarmInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The ViewDataAcknowledgwAlarm item info.
            /// </summary>
            [RepositoryItemInfo("7be52f43-2cea-4c12-b472-9fa8a26afb76")]
            public virtual RepoItemInfo ViewDataAcknowledgwAlarmInfo
            {
                get
                {
                    return _viewdataacknowledgwalarmInfo;
                }
            }
        }

        /// <summary>
        /// The SQLdmDesktopClientAppFolder folder.
        /// </summary>
        [RepositoryFolder("9545f389-3161-4094-a144-bf9e8a5703bd")]
        public partial class SQLdmDesktopClientAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _snoozealertsInfo;
            RepoItemInfo _snoozealerts_contextmenuInfo;
            RepoItemInfo _maintenancemodeInfo;
            RepoItemInfo _enablecontextmenuitemInfo;
            RepoItemInfo _disablecontextmenuitemInfo;
            RepoItemInfo _scheduleconextmenuitemInfo;
            RepoItemInfo _connecttosqldmrepositoryInfo;
            RepoItemInfo _maintenancemodeenablemenuitemInfo;
            RepoItemInfo _maintenancemodedisablemenuitemInfo;
            RepoItemInfo _maintenancemodeschedulemenuitemInfo;

            /// <summary>
            /// Creates a new SQLdmDesktopClient  folder.
            /// </summary>
            public SQLdmDesktopClientAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SQLdmDesktopClient", "/contextmenu[@processname='SQLdmDesktopClient']", parentFolder, 30000, null, false, "9545f389-3161-4094-a144-bf9e8a5703bd", "")
            {
                _snoozealertsInfo = new RepoItemInfo(this, "SnoozeAlerts", "menuitem[@automationid='snoozeAllAlertsToolMenu']//text[@caption='Snooze Alerts...']", 30000, null, "5d3e6767-4d33-45b3-b059-d4982440ae5e");
                _snoozealerts_contextmenuInfo = new RepoItemInfo(this, "SnoozeAlerts_ContextMenu", "menuitem[@accessiblename='Snooze Alerts...']", 30000, null, "b51f167c-fe06-4027-a22d-3ce03c36eaca");
                _maintenancemodeInfo = new RepoItemInfo(this, "MaintenanceMode", "menuitem[@accessiblename='Maintenance Mode']", 30000, null, "b29e0a59-6005-42dc-ae63-c3eb5abbba14");
                _enablecontextmenuitemInfo = new RepoItemInfo(this, "EnableContextMenuItem", "menuitem[@accessiblename='Enable']", 30000, null, "27d1dc94-e3b6-4035-932a-e92f4ab8a68a");
                _disablecontextmenuitemInfo = new RepoItemInfo(this, "DisableContextMenuItem", "menuitem[@accessiblename='Disable']", 30000, null, "1e898b15-b2a8-4c87-93f1-1f89883639a4");
                _scheduleconextmenuitemInfo = new RepoItemInfo(this, "ScheduleConextMenuItem", "menuitem[@accessiblename='Schedule...']", 30000, null, "0ac235e4-98db-471e-8531-4ae47970120a");
                _connecttosqldmrepositoryInfo = new RepoItemInfo(this, "ConnectToSQLDMRepository", "menuitem[@automationid='menuFileConnect']//text[@caption~'^Connect\\ to\\ SQLDM\\ Reposito']", 30000, null, "b0af1f43-8545-4ebc-87c7-28797f7524e0");
                _maintenancemodeenablemenuitemInfo = new RepoItemInfo(this, "MaintenanceModeEnableMenuItem", "menuitem[@automationid='maintenanceModeEnableButtonKey']", 30000, null, "d2c4305a-4698-46ad-84e5-a40c309c3fe6");
                _maintenancemodedisablemenuitemInfo = new RepoItemInfo(this, "MaintenanceModeDisableMenuItem", "menuitem[@automationid='maintenanceModeDisablettonKey']", 30000, null, "2f03dfc7-d8ce-4dd4-aab7-030571ed947d");
                _maintenancemodeschedulemenuitemInfo = new RepoItemInfo(this, "MaintenanceModeScheduleMenuItem", "menuitem[@automationid='maintenanceModeScheduleButtonKey']", 30000, null, "10182fd7-0261-4e59-9fd9-1dc53a646b16");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9545f389-3161-4094-a144-bf9e8a5703bd")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9545f389-3161-4094-a144-bf9e8a5703bd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SnoozeAlerts item.
            /// </summary>
            [RepositoryItem("5d3e6767-4d33-45b3-b059-d4982440ae5e")]
            public virtual Ranorex.Text SnoozeAlerts
            {
                get
                {
                    return _snoozealertsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SnoozeAlerts item info.
            /// </summary>
            [RepositoryItemInfo("5d3e6767-4d33-45b3-b059-d4982440ae5e")]
            public virtual RepoItemInfo SnoozeAlertsInfo
            {
                get
                {
                    return _snoozealertsInfo;
                }
            }

            /// <summary>
            /// The SnoozeAlerts_ContextMenu item.
            /// </summary>
            [RepositoryItem("b51f167c-fe06-4027-a22d-3ce03c36eaca")]
            public virtual Ranorex.MenuItem SnoozeAlerts_ContextMenu
            {
                get
                {
                    return _snoozealerts_contextmenuInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The SnoozeAlerts_ContextMenu item info.
            /// </summary>
            [RepositoryItemInfo("b51f167c-fe06-4027-a22d-3ce03c36eaca")]
            public virtual RepoItemInfo SnoozeAlerts_ContextMenuInfo
            {
                get
                {
                    return _snoozealerts_contextmenuInfo;
                }
            }

            /// <summary>
            /// The MaintenanceMode item.
            /// </summary>
            [RepositoryItem("b29e0a59-6005-42dc-ae63-c3eb5abbba14")]
            public virtual Ranorex.MenuItem MaintenanceMode
            {
                get
                {
                    return _maintenancemodeInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MaintenanceMode item info.
            /// </summary>
            [RepositoryItemInfo("b29e0a59-6005-42dc-ae63-c3eb5abbba14")]
            public virtual RepoItemInfo MaintenanceModeInfo
            {
                get
                {
                    return _maintenancemodeInfo;
                }
            }

            /// <summary>
            /// The EnableContextMenuItem item.
            /// </summary>
            [RepositoryItem("27d1dc94-e3b6-4035-932a-e92f4ab8a68a")]
            public virtual Ranorex.MenuItem EnableContextMenuItem
            {
                get
                {
                    return _enablecontextmenuitemInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The EnableContextMenuItem item info.
            /// </summary>
            [RepositoryItemInfo("27d1dc94-e3b6-4035-932a-e92f4ab8a68a")]
            public virtual RepoItemInfo EnableContextMenuItemInfo
            {
                get
                {
                    return _enablecontextmenuitemInfo;
                }
            }

            /// <summary>
            /// The DisableContextMenuItem item.
            /// </summary>
            [RepositoryItem("1e898b15-b2a8-4c87-93f1-1f89883639a4")]
            public virtual Ranorex.MenuItem DisableContextMenuItem
            {
                get
                {
                    return _disablecontextmenuitemInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The DisableContextMenuItem item info.
            /// </summary>
            [RepositoryItemInfo("1e898b15-b2a8-4c87-93f1-1f89883639a4")]
            public virtual RepoItemInfo DisableContextMenuItemInfo
            {
                get
                {
                    return _disablecontextmenuitemInfo;
                }
            }

            /// <summary>
            /// The ScheduleConextMenuItem item.
            /// </summary>
            [RepositoryItem("0ac235e4-98db-471e-8531-4ae47970120a")]
            public virtual Ranorex.MenuItem ScheduleConextMenuItem
            {
                get
                {
                    return _scheduleconextmenuitemInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ScheduleConextMenuItem item info.
            /// </summary>
            [RepositoryItemInfo("0ac235e4-98db-471e-8531-4ae47970120a")]
            public virtual RepoItemInfo ScheduleConextMenuItemInfo
            {
                get
                {
                    return _scheduleconextmenuitemInfo;
                }
            }

            /// <summary>
            /// The ConnectToSQLDMRepository item.
            /// </summary>
            [RepositoryItem("b0af1f43-8545-4ebc-87c7-28797f7524e0")]
            public virtual Ranorex.Text ConnectToSQLDMRepository
            {
                get
                {
                    return _connecttosqldmrepositoryInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ConnectToSQLDMRepository item info.
            /// </summary>
            [RepositoryItemInfo("b0af1f43-8545-4ebc-87c7-28797f7524e0")]
            public virtual RepoItemInfo ConnectToSQLDMRepositoryInfo
            {
                get
                {
                    return _connecttosqldmrepositoryInfo;
                }
            }

            /// <summary>
            /// The MaintenanceModeEnableMenuItem item.
            /// </summary>
            [RepositoryItem("d2c4305a-4698-46ad-84e5-a40c309c3fe6")]
            public virtual Ranorex.MenuItem MaintenanceModeEnableMenuItem
            {
                get
                {
                    return _maintenancemodeenablemenuitemInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MaintenanceModeEnableMenuItem item info.
            /// </summary>
            [RepositoryItemInfo("d2c4305a-4698-46ad-84e5-a40c309c3fe6")]
            public virtual RepoItemInfo MaintenanceModeEnableMenuItemInfo
            {
                get
                {
                    return _maintenancemodeenablemenuitemInfo;
                }
            }

            /// <summary>
            /// The MaintenanceModeDisableMenuItem item.
            /// </summary>
            [RepositoryItem("2f03dfc7-d8ce-4dd4-aab7-030571ed947d")]
            public virtual Ranorex.MenuItem MaintenanceModeDisableMenuItem
            {
                get
                {
                    return _maintenancemodedisablemenuitemInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MaintenanceModeDisableMenuItem item info.
            /// </summary>
            [RepositoryItemInfo("2f03dfc7-d8ce-4dd4-aab7-030571ed947d")]
            public virtual RepoItemInfo MaintenanceModeDisableMenuItemInfo
            {
                get
                {
                    return _maintenancemodedisablemenuitemInfo;
                }
            }

            /// <summary>
            /// The MaintenanceModeScheduleMenuItem item.
            /// </summary>
            [RepositoryItem("10182fd7-0261-4e59-9fd9-1dc53a646b16")]
            public virtual Ranorex.MenuItem MaintenanceModeScheduleMenuItem
            {
                get
                {
                    return _maintenancemodeschedulemenuitemInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MaintenanceModeScheduleMenuItem item info.
            /// </summary>
            [RepositoryItemInfo("10182fd7-0261-4e59-9fd9-1dc53a646b16")]
            public virtual RepoItemInfo MaintenanceModeScheduleMenuItemInfo
            {
                get
                {
                    return _maintenancemodeschedulemenuitemInfo;
                }
            }
        }

        /// <summary>
        /// The SnoozeAlertsDialogAppFolder folder.
        /// </summary>
        [RepositoryFolder("279bc91f-42af-40fc-a5aa-4e25b06755dc")]
        public partial class SnoozeAlertsDialogAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _snooozealerttimeInfo;
            RepoItemInfo _okbuttonInfo;

            /// <summary>
            /// Creates a new SnoozeAlertsDialog  folder.
            /// </summary>
            public SnoozeAlertsDialogAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SnoozeAlertsDialog", "/form[@controlname='SnoozeAlertsDialog']", parentFolder, 30000, null, true, "279bc91f-42af-40fc-a5aa-4e25b06755dc", "")
            {
                _snooozealerttimeInfo = new RepoItemInfo(this, "SnooozeAlertTime", "container[@controlname='contentStackPanel']//container[@controlname='snoozeMinutesSpinner']/text[@controlname='upDownEdit']", 30000, null, "873ac997-a48c-4835-9086-953b43cdf691");
                _okbuttonInfo = new RepoItemInfo(this, "OkButton", ".//button[@controlname='okButton']", 30000, null, "46c171f3-428e-4f1b-8d94-288c8183e9dc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("279bc91f-42af-40fc-a5aa-4e25b06755dc")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("279bc91f-42af-40fc-a5aa-4e25b06755dc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SnooozeAlertTime item.
            /// </summary>
            [RepositoryItem("873ac997-a48c-4835-9086-953b43cdf691")]
            public virtual Ranorex.Text SnooozeAlertTime
            {
                get
                {
                    return _snooozealerttimeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SnooozeAlertTime item info.
            /// </summary>
            [RepositoryItemInfo("873ac997-a48c-4835-9086-953b43cdf691")]
            public virtual RepoItemInfo SnooozeAlertTimeInfo
            {
                get
                {
                    return _snooozealerttimeInfo;
                }
            }

            /// <summary>
            /// The OkButton item.
            /// </summary>
            [RepositoryItem("46c171f3-428e-4f1b-8d94-288c8183e9dc")]
            public virtual Ranorex.Button OkButton
            {
                get
                {
                    return _okbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OkButton item info.
            /// </summary>
            [RepositoryItemInfo("46c171f3-428e-4f1b-8d94-288c8183e9dc")]
            public virtual RepoItemInfo OkButtonInfo
            {
                get
                {
                    return _okbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The RepositoryConnectionDialogAppFolder folder.
        /// </summary>
        [RepositoryFolder("045423ee-b2db-4e1b-9c8a-6f1ff05a9a01")]
        public partial class RepositoryConnectionDialogAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _authenticationdropdownlistInfo;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _connectbuttonInfo;

            /// <summary>
            /// Creates a new RepositoryConnectionDialog  folder.
            /// </summary>
            public RepositoryConnectionDialogAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RepositoryConnectionDialog", "/form[@controlname='RepositoryConnectionDialog']", parentFolder, 30000, null, true, "045423ee-b2db-4e1b-9c8a-6f1ff05a9a01", "")
            {
                _authenticationdropdownlistInfo = new RepoItemInfo(this, "AuthenticationDropDownList", "?/?/combobox[@controlname='authenticationDropDownList']", 30000, null, "dc9cff80-6ea0-4c96-b2c2-4485849f86c2");
                _usernameInfo = new RepoItemInfo(this, "Username", "container[@controlname='tableLayoutPanel1']/text[@controlname='userNameTextbox']/text[@accessiblerole='Text']", 30000, null, "5eeaae31-fd4d-4fbd-ac6c-515bb447de4b");
                _passwordInfo = new RepoItemInfo(this, "Password", "container[@controlname='tableLayoutPanel1']/text[@controlname='passwordTextbox']/text[@accessiblerole='Text']", 30000, null, "760aca35-edaa-457c-80e3-f1c2facc7ef0");
                _connectbuttonInfo = new RepoItemInfo(this, "ConnectButton", "button[@controlname='connectButton']", 30000, null, "e1850cb0-9ae2-477a-8e4b-4fe290ab7a5a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("045423ee-b2db-4e1b-9c8a-6f1ff05a9a01")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("045423ee-b2db-4e1b-9c8a-6f1ff05a9a01")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AuthenticationDropDownList item.
            /// </summary>
            [RepositoryItem("dc9cff80-6ea0-4c96-b2c2-4485849f86c2")]
            public virtual Ranorex.ComboBox AuthenticationDropDownList
            {
                get
                {
                    return _authenticationdropdownlistInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The AuthenticationDropDownList item info.
            /// </summary>
            [RepositoryItemInfo("dc9cff80-6ea0-4c96-b2c2-4485849f86c2")]
            public virtual RepoItemInfo AuthenticationDropDownListInfo
            {
                get
                {
                    return _authenticationdropdownlistInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("5eeaae31-fd4d-4fbd-ac6c-515bb447de4b")]
            public virtual Ranorex.Text Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("5eeaae31-fd4d-4fbd-ac6c-515bb447de4b")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("760aca35-edaa-457c-80e3-f1c2facc7ef0")]
            public virtual Ranorex.Text Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("760aca35-edaa-457c-80e3-f1c2facc7ef0")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The ConnectButton item.
            /// </summary>
            [RepositoryItem("e1850cb0-9ae2-477a-8e4b-4fe290ab7a5a")]
            public virtual Ranorex.Button ConnectButton
            {
                get
                {
                    return _connectbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ConnectButton item info.
            /// </summary>
            [RepositoryItemInfo("e1850cb0-9ae2-477a-8e4b-4fe290ab7a5a")]
            public virtual RepoItemInfo ConnectButtonInfo
            {
                get
                {
                    return _connectbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("97290bd8-21d4-4e4f-88b1-a8cf119886e4")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _sqlserverauthenticationInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "97290bd8-21d4-4e4f-88b1-a8cf119886e4", "")
            {
                _sqlserverauthenticationInfo = new RepoItemInfo(this, "SQLServerAuthentication", "listitem[@text='SQL Server Authentication']", 30000, null, "171bc8d2-a90c-447c-9463-c01be5ff98ac");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("97290bd8-21d4-4e4f-88b1-a8cf119886e4")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("97290bd8-21d4-4e4f-88b1-a8cf119886e4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SQLServerAuthentication item.
            /// </summary>
            [RepositoryItem("171bc8d2-a90c-447c-9463-c01be5ff98ac")]
            public virtual Ranorex.ListItem SQLServerAuthentication
            {
                get
                {
                    return _sqlserverauthenticationInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SQLServerAuthentication item info.
            /// </summary>
            [RepositoryItemInfo("171bc8d2-a90c-447c-9463-c01be5ff98ac")]
            public virtual RepoItemInfo SQLServerAuthenticationInfo
            {
                get
                {
                    return _sqlserverauthenticationInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}