///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomationSQLdm.OperatorSecurityRole
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the T721974Repo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("c0b1886f-194f-4804-ae68-99f28ac1402e")]
    public partial class T721974Repo : RepoGenBaseFolder
    {
        static T721974Repo instance = new T721974Repo();
        T721974RepoFolders.ApplicationAppFolder _application;
        T721974RepoFolders.ExceptionFormAppFolder _exceptionform;
        T721974RepoFolders.AddPermissionWizardAppFolder _addpermissionwizard;
        T721974RepoFolders.PermissionPropertyDialogAppFolder _permissionpropertydialog;
        T721974RepoFolders.SQLdmDesktopClientAppFolder _sqldmdesktopclient;
        T721974RepoFolders.SnoozeAlertsDialogAppFolder _snoozealertsdialog;

        /// <summary>
        /// Gets the singleton class instance representing the T721974Repo element repository.
        /// </summary>
        [RepositoryFolder("c0b1886f-194f-4804-ae68-99f28ac1402e")]
        public static T721974Repo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public T721974Repo() 
            : base("T721974Repo", "/", null, 0, false, "c0b1886f-194f-4804-ae68-99f28ac1402e", ".\\RepositoryImages\\T721974Repoc0b1886f.rximgres")
        {
            _application = new T721974RepoFolders.ApplicationAppFolder(this);
            _exceptionform = new T721974RepoFolders.ExceptionFormAppFolder(this);
            _addpermissionwizard = new T721974RepoFolders.AddPermissionWizardAppFolder(this);
            _permissionpropertydialog = new T721974RepoFolders.PermissionPropertyDialogAppFolder(this);
            _sqldmdesktopclient = new T721974RepoFolders.SQLdmDesktopClientAppFolder(this);
            _snoozealertsdialog = new T721974RepoFolders.SnoozeAlertsDialogAppFolder(this);
        }

#region Variables

        string _Constant_NewSqlUser = "";

        /// <summary>
        /// Gets or sets the value of variable Constant_NewSqlUser.
        /// </summary>
        [TestVariable("971340c3-a4a0-47b8-9d3b-fefd2c554fc1")]
        public string Constant_NewSqlUser
        {
            get { return _Constant_NewSqlUser; }
            set { _Constant_NewSqlUser = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c0b1886f-194f-4804-ae68-99f28ac1402e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Application folder.
        /// </summary>
        [RepositoryFolder("1a73f651-c755-42fc-8b6e-622d9bbcf5f6")]
        public virtual T721974RepoFolders.ApplicationAppFolder Application
        {
            get { return _application; }
        }

        /// <summary>
        /// The ExceptionForm folder.
        /// </summary>
        [RepositoryFolder("03260382-2f67-4d48-814d-38cb9e95e8d7")]
        public virtual T721974RepoFolders.ExceptionFormAppFolder ExceptionForm
        {
            get { return _exceptionform; }
        }

        /// <summary>
        /// The AddPermissionWizard folder.
        /// </summary>
        [RepositoryFolder("a22e5f92-0bb1-4450-adc1-c7b9588f7fac")]
        public virtual T721974RepoFolders.AddPermissionWizardAppFolder AddPermissionWizard
        {
            get { return _addpermissionwizard; }
        }

        /// <summary>
        /// The PermissionPropertyDialog folder.
        /// </summary>
        [RepositoryFolder("add75c9c-387f-4f83-b594-6e44d91f4f68")]
        public virtual T721974RepoFolders.PermissionPropertyDialogAppFolder PermissionPropertyDialog
        {
            get { return _permissionpropertydialog; }
        }

        /// <summary>
        /// The SQLdmDesktopClient folder.
        /// </summary>
        [RepositoryFolder("9545f389-3161-4094-a144-bf9e8a5703bd")]
        public virtual T721974RepoFolders.SQLdmDesktopClientAppFolder SQLdmDesktopClient
        {
            get { return _sqldmdesktopclient; }
        }

        /// <summary>
        /// The SnoozeAlertsDialog folder.
        /// </summary>
        [RepositoryFolder("279bc91f-42af-40fc-a5aa-4e25b06755dc")]
        public virtual T721974RepoFolders.SnoozeAlertsDialogAppFolder SnoozeAlertsDialog
        {
            get { return _snoozealertsdialog; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class T721974RepoFolders
    {
        /// <summary>
        /// The ApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("1a73f651-c755-42fc-8b6e-622d9bbcf5f6")]
        public partial class ApplicationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnadministrationInfo;
            RepoItemInfo _enablesecurityInfo;
            RepoItemInfo _applicationsecurityInfo;
            RepoItemInfo _btnaddusersInfo;
            RepoItemInfo _newwindowsuseraddedInfo;
            RepoItemInfo _btndeleteInfo;
            RepoItemInfo _newsqluseraddedInfo;

            /// <summary>
            /// Creates a new Application  folder.
            /// </summary>
            public ApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Application", "/form[@title~'^Idera\\ SQL\\ diagnostic\\ mana']", parentFolder, 30000, null, true, "1a73f651-c755-42fc-8b6e-622d9bbcf5f6", "")
            {
                _btnadministrationInfo = new RepoItemInfo(this, "btnAdministration", "statusbar[@automationid='statusBar']//container[@controlname='NavigationPaneControl']//button[@accessiblename='Administration']", 30000, null, "d5152b0d-4009-43f3-bc98-69da8be4ca7c");
                _enablesecurityInfo = new RepoItemInfo(this, "EnableSecurity", "statusbar[@automationid='statusBar']//container[@controlname='AdministrationView']//button[@accessiblename='Enable Security']", 30000, null, "f5eb38d9-4a59-4bf5-a1cc-3c7fe3ab33ab");
                _applicationsecurityInfo = new RepoItemInfo(this, "ApplicationSecurity", ".//container[@controlname='featureButtonAppSecurity']//text[@controlname='featureHeaderLabel']", 30000, null, "7beca8f1-156e-42cd-9e29-76177c54937a");
                _btnaddusersInfo = new RepoItemInfo(this, "btnAddUsers", ".//container[@controlname='contentPanel']//container[@accessiblename='Home']/toolbar[@accessiblename='Permissions']/button[@accessiblename='Add']", 30000, null, "d0736455-ddb6-4eea-aa8a-f74408840be1");
                _newwindowsuseraddedInfo = new RepoItemInfo(this, "NewWindowsUserAdded", "statusbar[@automationid='statusBar']//table[@accessiblename~'^\\ \\ \\ \\ \\ \\ \\ System\\ logins,\\ whi']//cell[@accessiblevalue='SIMPSONS\\administrator1']", 30000, null, "e83e5dc8-2e44-4b06-8733-50f149243c29");
                _btndeleteInfo = new RepoItemInfo(this, "btnDelete", "statusbar[@automationid='statusBar']//toolbar[@accessiblename='Permissions']/button[@accessiblename='Delete']", 30000, null, "f91739cf-b4a3-4344-a6d1-ce64cd55d567");
                _newsqluseraddedInfo = new RepoItemInfo(this, "NewSqlUserAdded", "statusbar[@automationid='statusBar']//table[@accessiblename~'^\\ \\ \\ \\ \\ \\ \\ System\\ logins,\\ whi']//cell[@accessiblevalue='sa1']", 30000, null, "172570af-8ff7-4fe3-85cb-8980091f5933");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1a73f651-c755-42fc-8b6e-622d9bbcf5f6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1a73f651-c755-42fc-8b6e-622d9bbcf5f6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnAdministration item.
            /// </summary>
            [RepositoryItem("d5152b0d-4009-43f3-bc98-69da8be4ca7c")]
            public virtual Ranorex.Button btnAdministration
            {
                get
                {
                    return _btnadministrationInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnAdministration item info.
            /// </summary>
            [RepositoryItemInfo("d5152b0d-4009-43f3-bc98-69da8be4ca7c")]
            public virtual RepoItemInfo btnAdministrationInfo
            {
                get
                {
                    return _btnadministrationInfo;
                }
            }

            /// <summary>
            /// The EnableSecurity item.
            /// </summary>
            [RepositoryItem("f5eb38d9-4a59-4bf5-a1cc-3c7fe3ab33ab")]
            public virtual Ranorex.Button EnableSecurity
            {
                get
                {
                    return _enablesecurityInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EnableSecurity item info.
            /// </summary>
            [RepositoryItemInfo("f5eb38d9-4a59-4bf5-a1cc-3c7fe3ab33ab")]
            public virtual RepoItemInfo EnableSecurityInfo
            {
                get
                {
                    return _enablesecurityInfo;
                }
            }

            /// <summary>
            /// The ApplicationSecurity item.
            /// </summary>
            [RepositoryItem("7beca8f1-156e-42cd-9e29-76177c54937a")]
            public virtual Ranorex.Text ApplicationSecurity
            {
                get
                {
                    return _applicationsecurityInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ApplicationSecurity item info.
            /// </summary>
            [RepositoryItemInfo("7beca8f1-156e-42cd-9e29-76177c54937a")]
            public virtual RepoItemInfo ApplicationSecurityInfo
            {
                get
                {
                    return _applicationsecurityInfo;
                }
            }

            /// <summary>
            /// The btnAddUsers item.
            /// </summary>
            [RepositoryItem("d0736455-ddb6-4eea-aa8a-f74408840be1")]
            public virtual Ranorex.Button btnAddUsers
            {
                get
                {
                    return _btnaddusersInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnAddUsers item info.
            /// </summary>
            [RepositoryItemInfo("d0736455-ddb6-4eea-aa8a-f74408840be1")]
            public virtual RepoItemInfo btnAddUsersInfo
            {
                get
                {
                    return _btnaddusersInfo;
                }
            }

            /// <summary>
            /// The NewWindowsUserAdded item.
            /// </summary>
            [RepositoryItem("e83e5dc8-2e44-4b06-8733-50f149243c29")]
            public virtual Ranorex.Cell NewWindowsUserAdded
            {
                get
                {
                    return _newwindowsuseraddedInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The NewWindowsUserAdded item info.
            /// </summary>
            [RepositoryItemInfo("e83e5dc8-2e44-4b06-8733-50f149243c29")]
            public virtual RepoItemInfo NewWindowsUserAddedInfo
            {
                get
                {
                    return _newwindowsuseraddedInfo;
                }
            }

            /// <summary>
            /// The btnDelete item.
            /// </summary>
            [RepositoryItem("f91739cf-b4a3-4344-a6d1-ce64cd55d567")]
            public virtual Ranorex.Button btnDelete
            {
                get
                {
                    return _btndeleteInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnDelete item info.
            /// </summary>
            [RepositoryItemInfo("f91739cf-b4a3-4344-a6d1-ce64cd55d567")]
            public virtual RepoItemInfo btnDeleteInfo
            {
                get
                {
                    return _btndeleteInfo;
                }
            }

            /// <summary>
            /// The NewSqlUserAdded item.
            /// </summary>
            [RepositoryItem("172570af-8ff7-4fe3-85cb-8980091f5933")]
            public virtual Ranorex.Cell NewSqlUserAdded
            {
                get
                {
                    return _newsqluseraddedInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The NewSqlUserAdded item info.
            /// </summary>
            [RepositoryItemInfo("172570af-8ff7-4fe3-85cb-8980091f5933")]
            public virtual RepoItemInfo NewSqlUserAddedInfo
            {
                get
                {
                    return _newsqluseraddedInfo;
                }
            }
        }

        /// <summary>
        /// The ExceptionFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("03260382-2f67-4d48-814d-38cb9e95e8d7")]
        public partial class ExceptionFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnyesInfo;

            /// <summary>
            /// Creates a new ExceptionForm  folder.
            /// </summary>
            public ExceptionFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ExceptionForm", "/form[@controlname='ExceptionMessageBoxForm']", parentFolder, 30000, null, true, "03260382-2f67-4d48-814d-38cb9e95e8d7", "")
            {
                _btnyesInfo = new RepoItemInfo(this, "btnYes", ".//button[@windowtext='&Yes']", 30000, null, "c5426114-da69-4c53-97eb-481dfbebee4b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("03260382-2f67-4d48-814d-38cb9e95e8d7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("03260382-2f67-4d48-814d-38cb9e95e8d7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnYes item.
            /// </summary>
            [RepositoryItem("c5426114-da69-4c53-97eb-481dfbebee4b")]
            public virtual Ranorex.Button btnYes
            {
                get
                {
                    return _btnyesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnYes item info.
            /// </summary>
            [RepositoryItemInfo("c5426114-da69-4c53-97eb-481dfbebee4b")]
            public virtual RepoItemInfo btnYesInfo
            {
                get
                {
                    return _btnyesInfo;
                }
            }
        }

        /// <summary>
        /// The AddPermissionWizardAppFolder folder.
        /// </summary>
        [RepositoryFolder("a22e5f92-0bb1-4450-adc1-c7b9588f7fac")]
        public partial class AddPermissionWizardAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnnextInfo;
            RepoItemInfo _txtusernameInfo;
            RepoItemInfo _viewdataacknowledgwalarmInfo;
            RepoItemInfo _availableserversInfo;
            RepoItemInfo _buttonaddInfo;
            RepoItemInfo _buttonfinishInfo;
            RepoItemInfo _comboboxuserpagecmbbxauthenticationInfo;

            /// <summary>
            /// Creates a new AddPermissionWizard  folder.
            /// </summary>
            public AddPermissionWizardAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AddPermissionWizard", "/form[@controlname='AddPermissionWizard']", parentFolder, 30000, null, true, "a22e5f92-0bb1-4450-adc1-c7b9588f7fac", "")
            {
                _btnnextInfo = new RepoItemInfo(this, "btnNext", ".//button[@windowtext='&Next >']", 30000, null, "b6d30a78-1b49-4eb7-8236-6f4bebfac5cc");
                _txtusernameInfo = new RepoItemInfo(this, "txtUserName", "container[@controlname='_wizard']//text[@accessiblerole='Text']", 30000, null, "3f200e22-97eb-4912-98b9-b25b78ec61d7");
                _viewdataacknowledgwalarmInfo = new RepoItemInfo(this, "ViewDataAcknowledgwAlarm", "container[@controlname='_wizard']//radiobutton[@controlname='_permissionPageRdBtnReadOnlyPlus']", 30000, null, "fce969f7-f146-4767-ba28-711b708ee06a");
                _availableserversInfo = new RepoItemInfo(this, "AvailableServers", "container[@controlname='_wizard']//container[@controlname='_serversListSelectorControl']//list[@controlname='listBoxAvailable']", 30000, null, "7a396840-f02f-4960-aaab-3ff9800f57cb");
                _buttonaddInfo = new RepoItemInfo(this, "ButtonAdd", "container[@controlname='_wizard']//container[@controlname='tableLayoutPanel2']/button[@controlname='buttonAdd']", 30000, null, "62e75094-e409-4073-9734-0795032f3f0f");
                _buttonfinishInfo = new RepoItemInfo(this, "ButtonFinish", ".//button[@text='Finish']", 30000, null, "dff72719-a352-42e6-be7d-349d3ce825a7");
                _comboboxuserpagecmbbxauthenticationInfo = new RepoItemInfo(this, "ComboBoxUserPageCmbBxAuthentication", "container[@controlname='_wizard']//combobox[@controlname='_userPageCmbBxAuthentication']", 30000, null, "01141426-8c31-45b3-b8d8-e14b26cd328f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a22e5f92-0bb1-4450-adc1-c7b9588f7fac")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a22e5f92-0bb1-4450-adc1-c7b9588f7fac")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnNext item.
            /// </summary>
            [RepositoryItem("b6d30a78-1b49-4eb7-8236-6f4bebfac5cc")]
            public virtual Ranorex.Button btnNext
            {
                get
                {
                    return _btnnextInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnNext item info.
            /// </summary>
            [RepositoryItemInfo("b6d30a78-1b49-4eb7-8236-6f4bebfac5cc")]
            public virtual RepoItemInfo btnNextInfo
            {
                get
                {
                    return _btnnextInfo;
                }
            }

            /// <summary>
            /// The txtUserName item.
            /// </summary>
            [RepositoryItem("3f200e22-97eb-4912-98b9-b25b78ec61d7")]
            public virtual Ranorex.Text txtUserName
            {
                get
                {
                    return _txtusernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtUserName item info.
            /// </summary>
            [RepositoryItemInfo("3f200e22-97eb-4912-98b9-b25b78ec61d7")]
            public virtual RepoItemInfo txtUserNameInfo
            {
                get
                {
                    return _txtusernameInfo;
                }
            }

            /// <summary>
            /// The ViewDataAcknowledgwAlarm item.
            /// </summary>
            [RepositoryItem("fce969f7-f146-4767-ba28-711b708ee06a")]
            public virtual Ranorex.RadioButton ViewDataAcknowledgwAlarm
            {
                get
                {
                    return _viewdataacknowledgwalarmInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The ViewDataAcknowledgwAlarm item info.
            /// </summary>
            [RepositoryItemInfo("fce969f7-f146-4767-ba28-711b708ee06a")]
            public virtual RepoItemInfo ViewDataAcknowledgwAlarmInfo
            {
                get
                {
                    return _viewdataacknowledgwalarmInfo;
                }
            }

            /// <summary>
            /// The AvailableServers item.
            /// </summary>
            [RepositoryItem("7a396840-f02f-4960-aaab-3ff9800f57cb")]
            public virtual Ranorex.List AvailableServers
            {
                get
                {
                    return _availableserversInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The AvailableServers item info.
            /// </summary>
            [RepositoryItemInfo("7a396840-f02f-4960-aaab-3ff9800f57cb")]
            public virtual RepoItemInfo AvailableServersInfo
            {
                get
                {
                    return _availableserversInfo;
                }
            }

            /// <summary>
            /// The ButtonAdd item.
            /// </summary>
            [RepositoryItem("62e75094-e409-4073-9734-0795032f3f0f")]
            public virtual Ranorex.Button ButtonAdd
            {
                get
                {
                    return _buttonaddInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonAdd item info.
            /// </summary>
            [RepositoryItemInfo("62e75094-e409-4073-9734-0795032f3f0f")]
            public virtual RepoItemInfo ButtonAddInfo
            {
                get
                {
                    return _buttonaddInfo;
                }
            }

            /// <summary>
            /// The ButtonFinish item.
            /// </summary>
            [RepositoryItem("dff72719-a352-42e6-be7d-349d3ce825a7")]
            public virtual Ranorex.Button ButtonFinish
            {
                get
                {
                    return _buttonfinishInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonFinish item info.
            /// </summary>
            [RepositoryItemInfo("dff72719-a352-42e6-be7d-349d3ce825a7")]
            public virtual RepoItemInfo ButtonFinishInfo
            {
                get
                {
                    return _buttonfinishInfo;
                }
            }

            /// <summary>
            /// The ComboBoxUserPageCmbBxAuthentication item.
            /// </summary>
            [RepositoryItem("01141426-8c31-45b3-b8d8-e14b26cd328f")]
            public virtual Ranorex.ComboBox ComboBoxUserPageCmbBxAuthentication
            {
                get
                {
                    return _comboboxuserpagecmbbxauthenticationInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBoxUserPageCmbBxAuthentication item info.
            /// </summary>
            [RepositoryItemInfo("01141426-8c31-45b3-b8d8-e14b26cd328f")]
            public virtual RepoItemInfo ComboBoxUserPageCmbBxAuthenticationInfo
            {
                get
                {
                    return _comboboxuserpagecmbbxauthenticationInfo;
                }
            }
        }

        /// <summary>
        /// The PermissionPropertyDialogAppFolder folder.
        /// </summary>
        [RepositoryFolder("add75c9c-387f-4f83-b594-6e44d91f4f68")]
        public partial class PermissionPropertyDialogAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btncancelInfo;
            RepoItemInfo _viewdataacknowledgwalarmInfo;

            /// <summary>
            /// Creates a new PermissionPropertyDialog  folder.
            /// </summary>
            public PermissionPropertyDialogAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PermissionPropertyDialog", "/form[@controlname='PermissionPropertyDialog']", parentFolder, 30000, null, true, "add75c9c-387f-4f83-b594-6e44d91f4f68", "")
            {
                _btncancelInfo = new RepoItemInfo(this, "btnCancel", "button[@controlname='_btnCancel']", 30000, null, "dfc1df6d-ec71-475d-8512-a56ded9c334d");
                _viewdataacknowledgwalarmInfo = new RepoItemInfo(this, "ViewDataAcknowledgwAlarm", ".//container[@controlname='_generalPropertyPage']//radiobutton[@controlname='_generalRdBtnReadOnlyPlus']", 30000, null, "7be52f43-2cea-4c12-b472-9fa8a26afb76");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("add75c9c-387f-4f83-b594-6e44d91f4f68")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("add75c9c-387f-4f83-b594-6e44d91f4f68")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnCancel item.
            /// </summary>
            [RepositoryItem("dfc1df6d-ec71-475d-8512-a56ded9c334d")]
            public virtual Ranorex.Button btnCancel
            {
                get
                {
                    return _btncancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnCancel item info.
            /// </summary>
            [RepositoryItemInfo("dfc1df6d-ec71-475d-8512-a56ded9c334d")]
            public virtual RepoItemInfo btnCancelInfo
            {
                get
                {
                    return _btncancelInfo;
                }
            }

            /// <summary>
            /// The ViewDataAcknowledgwAlarm item.
            /// </summary>
            [RepositoryItem("7be52f43-2cea-4c12-b472-9fa8a26afb76")]
            public virtual Ranorex.RadioButton ViewDataAcknowledgwAlarm
            {
                get
                {
                    return _viewdataacknowledgwalarmInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The ViewDataAcknowledgwAlarm item info.
            /// </summary>
            [RepositoryItemInfo("7be52f43-2cea-4c12-b472-9fa8a26afb76")]
            public virtual RepoItemInfo ViewDataAcknowledgwAlarmInfo
            {
                get
                {
                    return _viewdataacknowledgwalarmInfo;
                }
            }
        }

        /// <summary>
        /// The SQLdmDesktopClientAppFolder folder.
        /// </summary>
        [RepositoryFolder("9545f389-3161-4094-a144-bf9e8a5703bd")]
        public partial class SQLdmDesktopClientAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _snoozealertsInfo;

            /// <summary>
            /// Creates a new SQLdmDesktopClient  folder.
            /// </summary>
            public SQLdmDesktopClientAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SQLdmDesktopClient", "/contextmenu[@processname='SQLdmDesktopClient']", parentFolder, 30000, null, false, "9545f389-3161-4094-a144-bf9e8a5703bd", "")
            {
                _snoozealertsInfo = new RepoItemInfo(this, "SnoozeAlerts", "menuitem[@automationid='snoozeAllAlertsToolMenu']//text[@caption='Snooze Alerts...']", 30000, null, "5d3e6767-4d33-45b3-b059-d4982440ae5e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9545f389-3161-4094-a144-bf9e8a5703bd")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9545f389-3161-4094-a144-bf9e8a5703bd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SnoozeAlerts item.
            /// </summary>
            [RepositoryItem("5d3e6767-4d33-45b3-b059-d4982440ae5e")]
            public virtual Ranorex.Text SnoozeAlerts
            {
                get
                {
                    return _snoozealertsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SnoozeAlerts item info.
            /// </summary>
            [RepositoryItemInfo("5d3e6767-4d33-45b3-b059-d4982440ae5e")]
            public virtual RepoItemInfo SnoozeAlertsInfo
            {
                get
                {
                    return _snoozealertsInfo;
                }
            }
        }

        /// <summary>
        /// The SnoozeAlertsDialogAppFolder folder.
        /// </summary>
        [RepositoryFolder("279bc91f-42af-40fc-a5aa-4e25b06755dc")]
        public partial class SnoozeAlertsDialogAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _snooozealerttimeInfo;
            RepoItemInfo _okbuttonInfo;

            /// <summary>
            /// Creates a new SnoozeAlertsDialog  folder.
            /// </summary>
            public SnoozeAlertsDialogAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SnoozeAlertsDialog", "/form[@controlname='SnoozeAlertsDialog']", parentFolder, 30000, null, true, "279bc91f-42af-40fc-a5aa-4e25b06755dc", "")
            {
                _snooozealerttimeInfo = new RepoItemInfo(this, "SnooozeAlertTime", "container[@controlname='contentStackPanel']//container[@controlname='snoozeMinutesSpinner']/text[@controlname='upDownEdit']", 30000, null, "873ac997-a48c-4835-9086-953b43cdf691");
                _okbuttonInfo = new RepoItemInfo(this, "OkButton", ".//button[@controlname='okButton']", 30000, null, "46c171f3-428e-4f1b-8d94-288c8183e9dc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("279bc91f-42af-40fc-a5aa-4e25b06755dc")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("279bc91f-42af-40fc-a5aa-4e25b06755dc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SnooozeAlertTime item.
            /// </summary>
            [RepositoryItem("873ac997-a48c-4835-9086-953b43cdf691")]
            public virtual Ranorex.Text SnooozeAlertTime
            {
                get
                {
                    return _snooozealerttimeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SnooozeAlertTime item info.
            /// </summary>
            [RepositoryItemInfo("873ac997-a48c-4835-9086-953b43cdf691")]
            public virtual RepoItemInfo SnooozeAlertTimeInfo
            {
                get
                {
                    return _snooozealerttimeInfo;
                }
            }

            /// <summary>
            /// The OkButton item.
            /// </summary>
            [RepositoryItem("46c171f3-428e-4f1b-8d94-288c8183e9dc")]
            public virtual Ranorex.Button OkButton
            {
                get
                {
                    return _okbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OkButton item info.
            /// </summary>
            [RepositoryItemInfo("46c171f3-428e-4f1b-8d94-288c8183e9dc")]
            public virtual RepoItemInfo OkButtonInfo
            {
                get
                {
                    return _okbuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}