///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomationSQLdm.Application
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AppRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("2d96b086-6c2e-4921-95da-54b21d7428c0")]
    public partial class AppRepo : RepoGenBaseFolder
    {
        static AppRepo instance = new AppRepo();
        AppRepoFolders.IderaSQLdmRepoAppFolder _iderasqldmrepo;

        /// <summary>
        /// Gets the singleton class instance representing the AppRepo element repository.
        /// </summary>
        [RepositoryFolder("2d96b086-6c2e-4921-95da-54b21d7428c0")]
        public static AppRepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AppRepo() 
            : base("AppRepo", "/", null, 0, false, "2d96b086-6c2e-4921-95da-54b21d7428c0", ".\\RepositoryImages\\AppRepo2d96b086.rximgres")
        {
            _iderasqldmrepo = new AppRepoFolders.IderaSQLdmRepoAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2d96b086-6c2e-4921-95da-54b21d7428c0")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The IderaSQLdmRepo folder.
        /// </summary>
        [RepositoryFolder("3740dcd6-d531-41d1-9c95-f02d217dce74")]
        public virtual AppRepoFolders.IderaSQLdmRepoAppFolder IderaSQLdmRepo
        {
            get { return _iderasqldmrepo; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class AppRepoFolders
    {
        /// <summary>
        /// The IderaSQLdmRepoAppFolder folder.
        /// </summary>
        [RepositoryFolder("3740dcd6-d531-41d1-9c95-f02d217dce74")]
        public partial class IderaSQLdmRepoAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lblsqldmtodayInfo;

            /// <summary>
            /// Creates a new IderaSQLdmRepo  folder.
            /// </summary>
            public IderaSQLdmRepoAppFolder(RepoGenBaseFolder parentFolder) :
                    base("IderaSQLdmRepo", "/form[@title~'^Idera\\ SQL\\ diagnostic\\ mana']", parentFolder, 30000, null, true, "3740dcd6-d531-41d1-9c95-f02d217dce74", "")
            {
                _lblsqldmtodayInfo = new RepoItemInfo(this, "lblSQLDMToday", ".//button[@automationid='toolBarTodayButton']/text[@caption='SQLDM Today']", 30000, null, "dc6dc38a-499d-48a4-96d2-e1b6e7640819");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3740dcd6-d531-41d1-9c95-f02d217dce74")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3740dcd6-d531-41d1-9c95-f02d217dce74")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The lblSQLDMToday item.
            /// </summary>
            [RepositoryItem("dc6dc38a-499d-48a4-96d2-e1b6e7640819")]
            public virtual Ranorex.Text lblSQLDMToday
            {
                get
                {
                    return _lblsqldmtodayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The lblSQLDMToday item info.
            /// </summary>
            [RepositoryItemInfo("dc6dc38a-499d-48a4-96d2-e1b6e7640819")]
            public virtual RepoItemInfo lblSQLDMTodayInfo
            {
                get
                {
                    return _lblsqldmtodayInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}